/*
 * Oxagorn v0.1.0 - Rust reimplementation of ARAGORN
 * tmrna_tags.rs - tmRNA tag peptide database
 *
 * Based on ARAGORN v1.2.41 by Dean Laslett
 * Author: Sunju Kim <n.e.coli.1822@gmail.com>
 */

use crate::types::{NTAG, NTAGMAX, TmrnaTagEntry};

/// Initialize database: first NTAG entries are filled, rest empty for new tags
const fn init_tagdatabase() -> [TmrnaTagEntry; NTAGMAX] {
    let entries: [TmrnaTagEntry; NTAG] = [
    TmrnaTagEntry::new("Acaryochloris marina", "ANNIVSFARQRTATAVA"),
    TmrnaTagEntry::new("Accumulibacter phosphatis", "ANDERFALAA"),
    TmrnaTagEntry::new("Acetobacter pasteurianus", "ANDNTEVLAVAA"),
    TmrnaTagEntry::new("Acetobacterium woodii", "AKTEKSYGLALAA"),
    TmrnaTagEntry::new("Acetohalobium arabaticum", "ANDNSYALAAA"),
    TmrnaTagEntry::new("Achromobacter xylosoxidans", "ANDERFALAA"),
    TmrnaTagEntry::new("Acidaminococcus fermentans", "ADDSYALAA"),
    TmrnaTagEntry::new("Acidaminococcus sp. D21", "AEDSYALAA"),
    TmrnaTagEntry::new("Acidimicrobium ferrooxidans", "AEPELALAA"),
    TmrnaTagEntry::new("Acidiphilium cryptum", "ANDNFEALAVAA"),
    TmrnaTagEntry::new("Acidithiobacillus caldus", "ANDSNYALAA"),
    TmrnaTagEntry::new("Acidithiobacillus ferrivorans", "ANDSNYALAA"),
    TmrnaTagEntry::new("Acidithiobacillus ferrooxidans", "ANDSNYALAA"),
    TmrnaTagEntry::new("Acidobacterium capsulatum", "ANNNLALAA"),
    TmrnaTagEntry::new("Acidobacterium Ellin6076", "ANTQFAYAA"),
    TmrnaTagEntry::new("Acidothermus cellulolyticus", "ANSSRADFALAA"),
    TmrnaTagEntry::new("Acidovorax avenae", "ANDERFALAA"),
    TmrnaTagEntry::new("Acidovorax citrulli", "ANDERFALAA"),
    TmrnaTagEntry::new("Acidovorax sp. JS42", "ANDERFALAA"),
    TmrnaTagEntry::new("Acidovorax sp. KKS102", "ANDERFALAA"),
    TmrnaTagEntry::new("Acinetobacter ADP1", "ANDETYALAA"),
    TmrnaTagEntry::new("Acinetobacter baumannii", "ANDETYALAA"),
    TmrnaTagEntry::new("Acinetobacter oleivorans", "ANDETYALAA"),
    TmrnaTagEntry::new("Acinetobacter sp. ADP1", "ANDETYALAA"),
    TmrnaTagEntry::new("Acinetobacter sp. SH024", "ANDETYALAA"),
    TmrnaTagEntry::new("Actinobacillus actinomycetemcomitans", "ANDEQYALAA"),
    TmrnaTagEntry::new("Actinobacillus pleuropneumoniae", "ANDEQYALAA"),
    TmrnaTagEntry::new("Actinobacillus succinogenes", "ANDEQYALAA"),
    TmrnaTagEntry::new("Actinobacillus suis", "ANDEQYALAA"),
    TmrnaTagEntry::new("Actinomyces naeslundii", "ADNTRTDFALAA"),
    TmrnaTagEntry::new("Actinoplanes missouriensis", "AKDNSRADFALAA"),
    TmrnaTagEntry::new("Actinoplanes sp. SE50/110", "ANSKFDADQYALAA"),
    TmrnaTagEntry::new("Actinosynnema mirum", "AKSNDQRAFALAA"),
    TmrnaTagEntry::new("Advenella kashmirensis", "ANDESYALAA"),
    TmrnaTagEntry::new("Aequorivita sublithincola", "GENNYALAA"),
    TmrnaTagEntry::new("Aerococcus urinae", "DKNESQSLAFAA"),
    TmrnaTagEntry::new("Aeromonas hydrophila 1", "ANDENYALAA"),
    TmrnaTagEntry::new("Aeromonas hydrophila 2", "ANDENYALAA"),
    TmrnaTagEntry::new("Aeromonas salmonicida", "ANDENYALAA"),
    TmrnaTagEntry::new("Aeromonas veronii", "ANDENYALAA"),
    TmrnaTagEntry::new("Aggregatibacter actinomycetemcomitans", "ANDEQYALAA"),
    TmrnaTagEntry::new("Aggregatibacter aphrophilus", "ANDEQYALAA"),
    TmrnaTagEntry::new("Agrobacterium fabrum", "ANDNNAKEYALAA"),
    TmrnaTagEntry::new("Agrobacterium radiobacter", "ANDNYAEARLAA"),
    TmrnaTagEntry::new("Agrobacterium sp. H13-3", "ANDNNAKEYALAA"),
    TmrnaTagEntry::new("Agrobacterium tumefaciens 1", "ANDNNAKEYALAA"),
    TmrnaTagEntry::new("Agrobacterium tumefaciens 2", "ANDNNAKECALAA"),
    TmrnaTagEntry::new("Agrobacterium vitis", "ANDNNAQGYAVAA"),
    TmrnaTagEntry::new("Akkermansia muciniphila", "AESNDLALAA"),
    TmrnaTagEntry::new("Alcaligenes faecalis", "ANDERFALAA"),
    TmrnaTagEntry::new("Alcaligenes viscolactis", "ANDERFALAA"),
    TmrnaTagEntry::new("Alcanivorax borkumensis", "ANDDSYALAA"),
    TmrnaTagEntry::new("Alcanivorax dieselolei", "ANDDTYALAA"),
    TmrnaTagEntry::new("Alicycliphilus denitrificans", "ANDERFALAA"),
    TmrnaTagEntry::new("Alicyclobacillus acidocaldarius", "GKANRFTTQNKLALAA"),
    TmrnaTagEntry::new("Aliivibrio salmonicida", "ANDENYALAA"),
    TmrnaTagEntry::new("Alistipes finegoldii", "GNNSYALAA"),
    TmrnaTagEntry::new("Alkalilimnicola ehrlichii", "ANDENYALAA"),
    TmrnaTagEntry::new("Alkaliphilus metalliredigenes", "ANDNYSLAAA"),
    TmrnaTagEntry::new("Alkaliphilus metalliredigens", "ANDNYSLAAA"),
    TmrnaTagEntry::new("Alkaliphilus oremlandii", "ANDNYALAA"),
    TmrnaTagEntry::new("Allochromatium vinosum", "ANDDNYALAA"),
    TmrnaTagEntry::new("alpha proteobacterium", "ANESYALAA"),
    TmrnaTagEntry::new("Alphaproteobacteria SAR-1", "ANDELALAA"),
    TmrnaTagEntry::new("Alteromonas macleodii", "ANDETYALAA"),
    TmrnaTagEntry::new("Alteromonas sp. SN2", "ANDENYALAA"),
    TmrnaTagEntry::new("Aminobacterium colombiense", "VNNNNYALAA"),
    TmrnaTagEntry::new("Ammonifex degensii", "ANNERVALAA"),
    TmrnaTagEntry::new("Amoebophilus asiaticus", "GNNQVALAA"),
    TmrnaTagEntry::new("Amphibacillus xylanus", "GKTNNYSLAAA"),
    TmrnaTagEntry::new("Amycolatopsis mediterranei", "ADSSQREFALAA"),
    TmrnaTagEntry::new("Amycolicicoccus subflavus", "ADNAQRSQSDFALAA"),
    TmrnaTagEntry::new("Anabaena variabilis", "ANNIVKFARKDALVAA"),
    TmrnaTagEntry::new("Anaerobaculum mobile", "ANENYALAA"),
    TmrnaTagEntry::new("Anaerococcus prevotii", "ANNNSEANFALAA"),
    TmrnaTagEntry::new("Anaerolinea thermophila", "VRKSGCRSGRSRTERKRAFGP"),
    TmrnaTagEntry::new("Anaeromyxobacter dehalogenans", "ANEPMALAA"),
    TmrnaTagEntry::new("Anaeromyxobacter sp. Fw109-5", "ANEPMALAA"),
    TmrnaTagEntry::new("Anaeromyxobacter sp. K", "ANEPMALAA"),
    TmrnaTagEntry::new("Anaplasma centrale", "ANDDFVAANDNMETAFVAAA"),
    TmrnaTagEntry::new("Anaplasma marginale", "ANDDFVAANDNMETAFVAAA"),
    TmrnaTagEntry::new("Anaplasma phagocytophilum", "ANDDFVAANDNVETAFVAAA"),
    TmrnaTagEntry::new("Anoxybacillus flavithermus", "GKENYALAA"),
    TmrnaTagEntry::new("Aquifex aeolicus", "APEAELALAA"),
    TmrnaTagEntry::new("Arcanobacterium haemolyticum", "ANKQKSDFALAA"),
    TmrnaTagEntry::new("Arcobacter butzleri", "ANNTNYAPAYAKAA"),
    TmrnaTagEntry::new("Arcobacter nitrofigilis", "ANNTNYAPAYAKVA"),
    TmrnaTagEntry::new("Arcobacter sp. L", "ANNTNYAPAYAKAA"),
    TmrnaTagEntry::new("Aromatoleum aromaticum", "ANDERFAVAA"),
    TmrnaTagEntry::new("Arthrobacter arilaitensis", "AESKRTDFALAA"),
    TmrnaTagEntry::new("Arthrobacter aurescens", "AESKRTDFALAA"),
    TmrnaTagEntry::new("Arthrobacter chlorophenolicus", "AESKRTDFALAA"),
    TmrnaTagEntry::new("Arthrobacter FB24", "AKQTRTDFALAA"),
    TmrnaTagEntry::new("Arthrobacter phenanthrenivorans", "AESKRTDFALAA"),
    TmrnaTagEntry::new("Arthrobacter sp. FB24", "AKQTRTDFALAA"),
    TmrnaTagEntry::new("Arthrobacter sp. Rue61a", "AESKRTDFALAA"),
    TmrnaTagEntry::new("Arthromitus sp. SFB-mouse-Japan", "DKNYSLQAA"),
    TmrnaTagEntry::new("Arthromitus sp. SFB-rat-Yit", "DKNYSLQAA"),
    TmrnaTagEntry::new("Azoarcus BH72", "ANDERFALAA"),
    TmrnaTagEntry::new("Azoarcus EbN1", "ANDERFAVAA"),
    TmrnaTagEntry::new("Azoarcus sp. BH72", "ANDERFALAA"),
    TmrnaTagEntry::new("Azobacteroides pseudotrichonymphae", "GENFYALAA"),
    TmrnaTagEntry::new("Azorhizobium caulinodans", "ANDNYAPVAVAA"),
    TmrnaTagEntry::new("Azospira oryzae", "ANDERFAIAA"),
    TmrnaTagEntry::new("Azospirillum brasilense", "ANDNVAPVAVAA"),
    TmrnaTagEntry::new("Azospirillum lipoferum", "ANDNVAQARLAA"),
    TmrnaTagEntry::new("Azospirillum sp. B510", "ANDNVAQARLAA"),
    TmrnaTagEntry::new("Azotobacter vinelandii", "ANDDNYALAA"),
    TmrnaTagEntry::new("Bacillus amyloliquefaciens", "GKTKSFNQNLALAA"),
    TmrnaTagEntry::new("Bacillus anthracis", "GKQNNLSLAA"),
    TmrnaTagEntry::new("Bacillus atrophaeus", "GKTKSFNQNLALAA"),
    TmrnaTagEntry::new("Bacillus cellulosilyticus", "GKQEDNFAFAA"),
    TmrnaTagEntry::new("Bacillus cereus", "GKQNNLSLAA"),
    TmrnaTagEntry::new("Bacillus clausii", "GKENNNFALAA"),
    TmrnaTagEntry::new("Bacillus coagulans", "GKSNTKLALAA"),
    TmrnaTagEntry::new("Bacillus cytotoxicus", "GKQQNNFALAA"),
    TmrnaTagEntry::new("Bacillus halodurans", "GKENNNFALAA"),
    TmrnaTagEntry::new("Bacillus licheniformis", "GKSNQNLALAA"),
    TmrnaTagEntry::new("Bacillus megaterium", "GKSNNNFALAA"),
    TmrnaTagEntry::new("Bacillus phage", "AKLNITNNELQVA"),
    TmrnaTagEntry::new("Bacillus pumilus", "GKTKSFNQNLALAA"),
    TmrnaTagEntry::new("Bacillus selenitireducens", "GKQDNDFALAAA"),
    TmrnaTagEntry::new("Bacillus stearothermophilus", "GKQNYALAA"),
    TmrnaTagEntry::new("Bacillus subtilis", "GKTNSFNQNVALAA"),
    TmrnaTagEntry::new("Bacillus thuringiensis", "GKQNNLSLAA"),
    TmrnaTagEntry::new("Bacillus weihenstephanensis", "GKQNNLSLAA"),
    TmrnaTagEntry::new("Bacillusphage G", "AKLNITNNELQVA"),
    TmrnaTagEntry::new("Bacteriovorax marinus", "AESNFAPAMAA"),
    TmrnaTagEntry::new("Bacteroides fragilis", "GETNYALAA"),
    TmrnaTagEntry::new("Bacteroides helcogenes", "GENNYALAA"),
    TmrnaTagEntry::new("Bacteroides salanitronis", "GNENYALAA"),
    TmrnaTagEntry::new("Bacteroides thetaiotaomicron", "GETNYALAA"),
    TmrnaTagEntry::new("Bacteroides vulgatus", "GNENYALAA"),
    TmrnaTagEntry::new("Bartonella bacilliformis", "ANDNYAEARLAA"),
    TmrnaTagEntry::new("Bartonella clarridgeiae", "ANDNYAEARLIAA"),
    TmrnaTagEntry::new("Bartonella grahamii", "ANDNYAEARLAA"),
    TmrnaTagEntry::new("Bartonella henselae", "ANDNYAEARLAA"),
    TmrnaTagEntry::new("Bartonella quintana", "ANDNYAEARLAA"),
    TmrnaTagEntry::new("Bartonella tribocorum", "ANDNYAEARLAA"),
    TmrnaTagEntry::new("Baumannia cicadellinicola", "ANNSQYESVALAA"),
    TmrnaTagEntry::new("Bdellovibrio bacteriovorus", "GNDYALAA"),
    TmrnaTagEntry::new("Beijerinckia indica", "ANDNYAPVAVAA"),
    TmrnaTagEntry::new("Belliella baltica", "GESNYAMAA"),
    TmrnaTagEntry::new("Beutenbergia cavernae", "ADSKRTDFALAA"),
    TmrnaTagEntry::new("Bifidobacterium adolescentis", "AKSNRTEFALAA"),
    TmrnaTagEntry::new("Bifidobacterium animalis", "AKSNRTEFALAA"),
    TmrnaTagEntry::new("Bifidobacterium asteroides", "AKSNRTEFALAA"),
    TmrnaTagEntry::new("Bifidobacterium bifidum", "AKSNRTEFALAA"),
    TmrnaTagEntry::new("Bifidobacterium breve", "AKSNRTEFALAA"),
    TmrnaTagEntry::new("Bifidobacterium dentium", "AKSNRTEFALAA"),
    TmrnaTagEntry::new("Bifidobacterium longum", "AKSNRTEFALAA"),
    TmrnaTagEntry::new("Blastococcus saxobsidens", "ADSNRADYALAA"),
    TmrnaTagEntry::new("Blattabacterium sp. (Blaberus giganteus)", "GEKEYAFAA"),
    TmrnaTagEntry::new("Blattabacterium sp. (Blattella germanica) Bge", "GEQQYAFAA"),
    TmrnaTagEntry::new("Blattabacterium sp. (Cryptocercus punctulatus)", "GEKQYAFAA"),
    TmrnaTagEntry::new("Blattabacterium sp. (Mastotermes darwiniensis)", "GEKQYAFAA"),
    TmrnaTagEntry::new("Blattabacterium sp. (Periplaneta americana)", "GEKQYAFAA"),
    TmrnaTagEntry::new("Blochmannia floridanus", "AKNKYNEPVALAA"),
    TmrnaTagEntry::new("Blochmannia pennsylvanicus", "ANNTTYRESVALAA"),
    TmrnaTagEntry::new("Blochmannia vafer", "ANYNYNESAALAA"),
    TmrnaTagEntry::new("Bolidomonas pacifica chloroplast", "ANNILAFNRKSLSFA"),
    TmrnaTagEntry::new("Bordetella avium", "ANDERFALAA"),
    TmrnaTagEntry::new("Bordetella bronchiseptica", "ANDERFALAA"),
    TmrnaTagEntry::new("Bordetella parapertussis", "ANDERFALAA"),
    TmrnaTagEntry::new("Bordetella pertussis", "ANDERFALAA"),
    TmrnaTagEntry::new("Bordetella petrii", "ANDERFALAA"),
    TmrnaTagEntry::new("Borrelia afzelii", "AKNNNFTSSNLVMAA"),
    TmrnaTagEntry::new("Borrelia bissettii", "AKNNNFTSSNLVMAA"),
    TmrnaTagEntry::new("Borrelia burgdorferi", "AKNNNFTSSNLVMAA"),
    TmrnaTagEntry::new("Borrelia crocidurae", "AKNNNFTSSDLVMAA"),
    TmrnaTagEntry::new("Borrelia duttonii", "AKNNNFTSSDLVMAA"),
    TmrnaTagEntry::new("Borrelia garinii", "AKNNNFTSSNLVMAA"),
    TmrnaTagEntry::new("Borrelia hermsii", "ARNNNFTSSNLVMAA"),
    TmrnaTagEntry::new("Borrelia recurrentis", "AKNNNFTSSDLVMAA"),
    TmrnaTagEntry::new("Borrelia turicatae", "AKNNNFTSSNLVMAA"),
    TmrnaTagEntry::new("Brachybacterium faecium", "AEPKRTDFALAA"),
    TmrnaTagEntry::new("Brachyspira hyodysenteriae", "ADEYALAA"),
    TmrnaTagEntry::new("Brachyspira intermedia", "ADEYALAA"),
    TmrnaTagEntry::new("Brachyspira murdochii", "ADEYALAA"),
    TmrnaTagEntry::new("Brachyspira pilosicoli", "ADEYALAA"),
    TmrnaTagEntry::new("Bradyrhizobium japonicum", "ANDNFAPVAQAA"),
    TmrnaTagEntry::new("Bradyrhizobium sp. BTAi1", "ANDNFAPVAQAA"),
    TmrnaTagEntry::new("Bradyrhizobium sp. ORS 278", "ANDNFAPVAQAA"),
    TmrnaTagEntry::new("Bradyrhizobium sp. S23321", "ANDNFAPVAQAA"),
    TmrnaTagEntry::new("Brevibacillus brevis", "GNKQLSLAA"),
    TmrnaTagEntry::new("Brevibacterium linens", "AKSNNRTDFALAA"),
    TmrnaTagEntry::new("Brucella abortus", "ANDNNAQGYALAA"),
    TmrnaTagEntry::new("Brucella canis", "ANDNNAQGYALAA"),
    TmrnaTagEntry::new("Brucella ceti", "ANDNNAQGYALAA"),
    TmrnaTagEntry::new("Brucella melitensis", "ANDNNAQGYALAA"),
    TmrnaTagEntry::new("Brucella ovis", "ANDNNAQGYALAA"),
    TmrnaTagEntry::new("Brucella suis", "ANDNNAQGYALAA"),
    TmrnaTagEntry::new("Buchnera aphidicola 1", "ANNKQNYALAA"),
    TmrnaTagEntry::new("Buchnera aphidicola 2", "ANNKQNYALAA"),
    TmrnaTagEntry::new("Buchnera aphidicola 3", "AKQNQYALAA"),
    TmrnaTagEntry::new("Burkholderia ambifaria", "ANDDTFALAA"),
    TmrnaTagEntry::new("Burkholderia cenocepacia", "ANDDTFALAA"),
    TmrnaTagEntry::new("Burkholderia cepacia", "ANDDTFALAA"),
    TmrnaTagEntry::new("Burkholderia fungorum", "ANDDTFALAA"),
    TmrnaTagEntry::new("Burkholderia gladioli", "ANDETFALAA"),
    TmrnaTagEntry::new("Burkholderia glumae", "ANDDTFALAA"),
    TmrnaTagEntry::new("Burkholderia graminis", "ANDDTFALAA"),
    TmrnaTagEntry::new("Burkholderia mallei", "ANDDTFALAA"),
    TmrnaTagEntry::new("Burkholderia multivorans", "ANDDTFALAA"),
    TmrnaTagEntry::new("Burkholderia phenoliruptrix", "ANDDTFALAA"),
    TmrnaTagEntry::new("Burkholderia phymatum", "ANDDTFALAA"),
    TmrnaTagEntry::new("Burkholderia phytofirmans", "ANDETFALAA"),
    TmrnaTagEntry::new("Burkholderia pseudomallei", "ANDDTFALAA"),
    TmrnaTagEntry::new("Burkholderia rhizoxinica", "ANDETYALAA"),
    TmrnaTagEntry::new("Burkholderia sp. 383", "ANDDTFALAA"),
    TmrnaTagEntry::new("Burkholderia sp. CCGE1001", "ANDDTFALAA"),
    TmrnaTagEntry::new("Burkholderia sp. CCGE1002", "ANDDTFALAA"),
    TmrnaTagEntry::new("Burkholderia sp. YI23", "ANDDTFALAA"),
    TmrnaTagEntry::new("Burkholderia thailandensis", "ANDDTFALAA"),
    TmrnaTagEntry::new("Burkholderia vietnamiensis", "ANDDTFALAA"),
    TmrnaTagEntry::new("Burkholderia xenovorans", "ANDDTFALAA"),
    TmrnaTagEntry::new("Butyrivibrio proteoclasticus", "ANDNLALAA"),
    TmrnaTagEntry::new("Caldicellulosiruptor bescii", "ADKAELALAA"),
    TmrnaTagEntry::new("Caldicellulosiruptor hydrothermalis", "ADRTELALAA"),
    TmrnaTagEntry::new("Caldicellulosiruptor kristjanssonii", "ADKAELALAA"),
    TmrnaTagEntry::new("Caldicellulosiruptor kronotskyensis", "ADKAELALAA"),
    TmrnaTagEntry::new("Caldicellulosiruptor lactoaceticus", "ADKAELALAA"),
    TmrnaTagEntry::new("Caldicellulosiruptor obsidiansis", "AEKPQLALAA"),
    TmrnaTagEntry::new("Caldicellulosiruptor owensensis", "AEKPQLALAA"),
    TmrnaTagEntry::new("Caldicellulosiruptor saccharolyticus", "ADKAELALAA"),
    TmrnaTagEntry::new("Caldilinea aerophila", "AKNTGKAFAFGTPATSVALAA"),
    TmrnaTagEntry::new("Caldisericum exile", "ADYSYALAA"),
    TmrnaTagEntry::new("Calditerrivibrio nitroreducens", "ANDEYALAAA"),
    TmrnaTagEntry::new("Campylobacter coli", "ANNVKFAPAYAKAA"),
    TmrnaTagEntry::new("Campylobacter concisus", "ANNVNFAPAYAKAA"),
    TmrnaTagEntry::new("Campylobacter curvus", "ANNVKFAPAYAKAA"),
    TmrnaTagEntry::new("Campylobacter fetus 2", "ANNVKFAPAYAKAA"),
    TmrnaTagEntry::new("Campylobacter hominis", "ANNAKFAPAYAKIA"),
    TmrnaTagEntry::new("Campylobacter jejuni", "ANNVKFAPAYAKAA"),
    TmrnaTagEntry::new("Campylobacter lari", "ANNVKFAPAYAKAA"),
    TmrnaTagEntry::new("Campylobacter upsaliensis", "ANNAKFAPAYAKVA"),
    TmrnaTagEntry::new("Candidatus atelocyanobacterium thalassa", "ANNIVSFKRVAVAA"),
    TmrnaTagEntry::new("Capnocytophaga canimorsus", "GENNYALAA"),
    TmrnaTagEntry::new("Capnocytophaga ochracea", "GENNYALAA"),
    TmrnaTagEntry::new("Carboxydothermus hydrogenoformans", "ANENYALAA"),
    TmrnaTagEntry::new("Cardinium endosymbiont", "VINNSRRCKFVALRKEEEEDDELRMAA"),
    TmrnaTagEntry::new("Carnobacterium maltaromaticum", "AKNNNNSYALAA"),
    TmrnaTagEntry::new("Carnobacterium sp. 17-4", "DKNNNNSYALAA"),
    TmrnaTagEntry::new("Catenulispora acidiphila", "ANKTQLKSQTAYGLAA"),
    TmrnaTagEntry::new("Catera virion", "ATDTDATVTDAEIEAFFAEEAAALV"),
    TmrnaTagEntry::new("Caulobacter crescentus", "ANDNFAEEFAVAA"),
    TmrnaTagEntry::new("Caulobacter segnis", "ANDNFAEEFAVAA"),
    TmrnaTagEntry::new("Caulobacter sp. K31", "ANDNFAEEFAIAA"),
    TmrnaTagEntry::new("Cellulomonas fimi", "ADNKRTDFALAA"),
    TmrnaTagEntry::new("Cellulomonas flavigena", "ADSKRTDFALAA"),
    TmrnaTagEntry::new("Cellulophaga algicola", "GENNYALAA"),
    TmrnaTagEntry::new("Cellulophaga lytica", "GENNYALAA"),
    TmrnaTagEntry::new("Cellvibrio gilvus", "ADSKRTDFALAA"),
    TmrnaTagEntry::new("Cellvibrio japonicus", "ANDDSYALAA"),
    TmrnaTagEntry::new("Chelativorans sp. BNC1", "ANDNYAEARLAA"),
    TmrnaTagEntry::new("Chitinophaga pinensis", "GESNYAMAA"),
    TmrnaTagEntry::new("Chlamydia muridarum", "AEPKAECEIISFADLNDLRVAA"),
    TmrnaTagEntry::new("Chlamydia psittaci", "AEPKAECEIISFSELSEQRLAA"),
    TmrnaTagEntry::new("Chlamydia trachomatis", "AEPKAECEIISFADLEDLRVAA"),
    TmrnaTagEntry::new("Chlamydophila abortus", "AEPKAKCEIISFSELSEQRLAA"),
    TmrnaTagEntry::new("Chlamydophila caviae", "AEPKAECEIISFSDLTEERLAA"),
    TmrnaTagEntry::new("Chlamydophila felis", "AEPKAECEIISFSDLTQERLAA"),
    TmrnaTagEntry::new("Chlamydophila pecorum", "AEPKAECEIISFSDLLVEERVAA"),
    TmrnaTagEntry::new("Chlamydophila pneumoniae", "AEPKAECEIISLFDSVEERLAA"),
    TmrnaTagEntry::new("Chlamydophila psittaci", "AEPKAECEIISFSELSEQRLAA"),
    TmrnaTagEntry::new("Chloracidobacterium thermophilum", "AETQELALAA"),
    TmrnaTagEntry::new("Chlorobaculum parvum", "ADDYSYAMAA"),
    TmrnaTagEntry::new("Chlorobium chlorochromatii", "ADDYSYAMAA"),
    TmrnaTagEntry::new("Chlorobium limicola", "ADDYSYAMAA"),
    TmrnaTagEntry::new("Chlorobium luteolum", "ADDYSYAMAA"),
    TmrnaTagEntry::new("Chlorobium phaeobacteroides", "ADDYSYAMAA"),
    TmrnaTagEntry::new("Chlorobium phaeovibrioides", "ADDYSYAMAA"),
    TmrnaTagEntry::new("Chlorobium tepidum", "ADDYSYAMAA"),
    TmrnaTagEntry::new("Chloroflexus aggregans", "ANNNARVQPRLALAA"),
    TmrnaTagEntry::new("Chloroflexus aurantiacus", "ANTNTRAQARLALAA"),
    TmrnaTagEntry::new("Chloroherpeton thalassium", "ADDYSYAMAA"),
    TmrnaTagEntry::new("Chromobacterium violaceum", "ANDETYALAA"),
    TmrnaTagEntry::new("Chromohalobacter salexigens", "ANDDNYAQGALAA"),
    TmrnaTagEntry::new("Chroococcidiopsis PCC6712", "ANNIVKFERQAVFA"),
    TmrnaTagEntry::new("Citrobacter koseri", "ANDENYALAA"),
    TmrnaTagEntry::new("Citrobacter rodentium", "ANDENYALAA"),
    TmrnaTagEntry::new("Clavibacter michiganensis", "ANNKQSSFVLAA"),
    TmrnaTagEntry::new("Cloacamonas acidaminovorans", "ANNNYALAA"),
    TmrnaTagEntry::new("Clostridiales genomosp.", "ANKNYSYAAA"),
    TmrnaTagEntry::new("Clostridium acetobutylicum", "DNENNLALAA"),
    TmrnaTagEntry::new("Clostridium acidurici", "ANDNYALAA"),
    TmrnaTagEntry::new("Clostridium beijerinckii", "AEDNFALAA"),
    TmrnaTagEntry::new("Clostridium botulinum", "ANDNFALAA"),
    TmrnaTagEntry::new("Clostridium cellulolyticum", "AKNDNFALAAA"),
    TmrnaTagEntry::new("Clostridium cellulovorans", "DENYLLAA"),
    TmrnaTagEntry::new("Clostridium clariflavum", "AENDNYALAAA"),
    TmrnaTagEntry::new("Clostridium difficile", "ADDNFAIAA"),
    TmrnaTagEntry::new("Clostridium kluyveri", "ENDNLALAA"),
    TmrnaTagEntry::new("Clostridium lentocellum", "AEDNLAIAA"),
    TmrnaTagEntry::new("Clostridium ljungdahlii", "ENNNENLALAA"),
    TmrnaTagEntry::new("Clostridium perfringens", "AEDNFALAA"),
    TmrnaTagEntry::new("Clostridium phytofermentans", "ANDNLAYAA"),
    TmrnaTagEntry::new("Clostridium saccharolyticum", "ANNNELALAA"),
    TmrnaTagEntry::new("Clostridium sp. BNL1100", "AKNDNFALAAA"),
    TmrnaTagEntry::new("Clostridium sp. SY8519", "AKEDNFELAMAA"),
    TmrnaTagEntry::new("Clostridium sticklandii", "ANENYALAA"),
    TmrnaTagEntry::new("Clostridium tetani", "ADDNFVLAA"),
    TmrnaTagEntry::new("Clostridium thermocellum", "ANEDNYALAAA"),
    TmrnaTagEntry::new("Collimonas fungivorans", "ANDNSYALAA"),
    TmrnaTagEntry::new("Colwellia psychrerythraea", "ANDDTFALAA"),
    TmrnaTagEntry::new("Colwellia sp", "ANDDTFALAA"),
    TmrnaTagEntry::new("Comamonas testosteroni", "ANDERFALAA"),
    TmrnaTagEntry::new("Conexibacter woesei", "ADSHEYALAA"),
    TmrnaTagEntry::new("Coprothermobacter proteolyticus", "AEPEFALAA"),
    TmrnaTagEntry::new("Coraliomargarita akajimensis", "GEEQFALAA"),
    TmrnaTagEntry::new("Corallococcus coralloides", "ANDNVELALAA"),
    TmrnaTagEntry::new("Coriobacterium glomerans", "GMAQTKIEPTRNPRARRRAQGNRISTGD"),
    TmrnaTagEntry::new("Corynebacterium aurimucosum", "AEKNSQRDYALAA"),
    TmrnaTagEntry::new("Corynebacterium diphtheriae", "AENTQRDYALAA"),
    TmrnaTagEntry::new("Corynebacterium efficiens", "AEKTQRDYALAA"),
    TmrnaTagEntry::new("Corynebacterium glutamicum", "AEKSQRDYALAA"),
    TmrnaTagEntry::new("Corynebacterium jeikeium", "AENTQRDYALAA"),
    TmrnaTagEntry::new("Corynebacterium kroppenstedtii", "AENTQRDYALAA"),
    TmrnaTagEntry::new("Corynebacterium pseudotuberculosis", "AEKTQRDYALAA"),
    TmrnaTagEntry::new("Corynebacterium resistens", "AENTQRDYALAA"),
    TmrnaTagEntry::new("Corynebacterium ulcerans", "AEKTQRDYALAA"),
    TmrnaTagEntry::new("Corynebacterium urealyticum", "AENTQRDYALAA"),
    TmrnaTagEntry::new("Corynebacterium variabile", "AENTQRDYALAA"),
    TmrnaTagEntry::new("Coxiella burnetii", "ANDSNYLQEAYA"),
    TmrnaTagEntry::new("Croceibacter atlanticus", "GENNYALAA"),
    TmrnaTagEntry::new("Crocosphaera watsonii", "ANNIVSFKRVAVAA"),
    TmrnaTagEntry::new("Cronobacter sakazakii", "ANDENYALAA"),
    TmrnaTagEntry::new("Cronobacter turicensis", "ANDENYALAA"),
    TmrnaTagEntry::new("Cryptobacterium curtum", "DNNKSFGRQYALAA"),
    TmrnaTagEntry::new("Cupriavidus metallidurans", "ANDERYALAA"),
    TmrnaTagEntry::new("Cupriavidus necator", "ANDERYALAA"),
    TmrnaTagEntry::new("Cupriavidus taiwanensis", "ANDERYALAA"),
    TmrnaTagEntry::new("Cyanidioschyzon merolae Chloroplast", "ANQILPFSIPVKHLAV"),
    TmrnaTagEntry::new("Cyanidium caldarium chloroplast", "ANNIIEISNIRKPALVV"),
    TmrnaTagEntry::new("Cyanobium gracile", "ANNIVRFSRQAAPVAA"),
    TmrnaTagEntry::new("Cyanobium sp. PCC 6904", "ANNIVRFSRQAAPVAA"),
    TmrnaTagEntry::new("Cyanobium sp. PCC 7009", "ANNIVRFSRQAAPVAA"),
    TmrnaTagEntry::new("Cyanophora paradoxa chloroplast", "ATNIVRFNRKAAFAV"),
    TmrnaTagEntry::new("Cyanothece sp. ATCC 51142", "ANNIVSFKRVAVAA"),
    TmrnaTagEntry::new("Cyanothece sp. PCC 7424", "ANNIVPFARKAAPVAA"),
    TmrnaTagEntry::new("Cyanothece sp. PCC 7425", "ANNIVPFARKAVAVA"),
    TmrnaTagEntry::new("Cyanothece sp. PCC 7822", "ANNIVPFARKSALVAA"),
    TmrnaTagEntry::new("Cyanothece sp. PCC 8801", "ANNIVSFKRVAVAA"),
    TmrnaTagEntry::new("Cyclobacterium marinum", "GESNYAMAA"),
    TmrnaTagEntry::new("Cycloclasticus sp. P1", "ANDDNYAIAA"),
    TmrnaTagEntry::new("Cytophaga hutchinsonii", "GEESYAMAA"),
    TmrnaTagEntry::new("Dechloromonas agitata", "ANDEQFAIAA"),
    TmrnaTagEntry::new("Dechloromonas aromatica", "ANDEQFAIAA"),
    TmrnaTagEntry::new("Dechlorosoma suillum", "ANDERFAIAA"),
    TmrnaTagEntry::new("Deferribacter desulfuricans", "ANDELALAA"),
    TmrnaTagEntry::new("Dehalococcoides ethenogenes", "GERELVLAG"),
    TmrnaTagEntry::new("Dehalococcoides sp. CBDB1", "GERELVLAG"),
    TmrnaTagEntry::new("Dehalococcoides sp. VS", "GERELVLAG"),
    TmrnaTagEntry::new("Dehalogenimonas lykanthroporepellens", "DAKEISAGLERFRRLKLEGREQKAG"),
    TmrnaTagEntry::new("Deinococcus deserti", "GNQNYALAA"),
    TmrnaTagEntry::new("Deinococcus geothermalis", "GNQNYALAA"),
    TmrnaTagEntry::new("Deinococcus gobiensis", "GNQNYALAA"),
    TmrnaTagEntry::new("Deinococcus maricopensis", "GNNNSTTFALAA"),
    TmrnaTagEntry::new("Deinococcus proteolyticus", "GENNYALAA"),
    TmrnaTagEntry::new("Deinococcus radiodurans", "GNQNYALAA"),
    TmrnaTagEntry::new("Delftia acidovorans", "ANDERFALAA"),
    TmrnaTagEntry::new("Delftia sp. Cs1-4", "ANDERFALAA"),
    TmrnaTagEntry::new("Denitrovibrio acetiphilus", "ANNEHTLAAA"),
    TmrnaTagEntry::new("Desulfarculus baarsii", "ADDYNYAVAA"),
    TmrnaTagEntry::new("Desulfatibacillum alkenivorans", "ADDYNYAMAA"),
    TmrnaTagEntry::new("Desulfitobacterium hafniense", "ANDDNYALAA"),
    TmrnaTagEntry::new("Desulfobacca acetoxidans", "ADNYGYALAA"),
    TmrnaTagEntry::new("Desulfobacterium autotrophicum", "ADDYNYAVAA"),
    TmrnaTagEntry::new("Desulfobacula toluolica", "ADDYNYAVAA"),
    TmrnaTagEntry::new("Desulfobulbus propionicus", "ADDYNYALAA"),
    TmrnaTagEntry::new("Desulfococcus oleovorans", "ADDYNYAVAA"),
    TmrnaTagEntry::new("Desulfohalobium retbaense", "ANDYDYALAA"),
    TmrnaTagEntry::new("Desulfomicrobium baculatum", "ANDNYDYAMAA"),
    TmrnaTagEntry::new("Desulfomonile tiedjei", "ANDYEYALAA"),
    TmrnaTagEntry::new("Desulforudis audaxviator", "AKNETYALAA"),
    TmrnaTagEntry::new("Desulfotalea psychrophila", "ADDYNYAVAA"),
    TmrnaTagEntry::new("Desulfotomaculum acetoxidans", "ANNDYALAA"),
    TmrnaTagEntry::new("Desulfotomaculum carboxydivorans", "ANEEYALAA"),
    TmrnaTagEntry::new("Desulfotomaculum kuznetsovii", "ANEEYALAA"),
    TmrnaTagEntry::new("Desulfotomaculum reducens", "ANEEYALAA"),
    TmrnaTagEntry::new("Desulfotomaculum ruminis", "ANEEYALAA"),
    TmrnaTagEntry::new("Desulfovibrio aespoeensis", "ANNDYDYAIAA"),
    TmrnaTagEntry::new("Desulfovibrio africanus", "ANDYNYSLAA"),
    TmrnaTagEntry::new("Desulfovibrio alaskensis", "ANNDYEYAMAA"),
    TmrnaTagEntry::new("Desulfovibrio desulfuricans", "ANNDYDYAYAA"),
    TmrnaTagEntry::new("Desulfovibrio desulfuricans 2 (G20)", "ANNDYEYAMAA"),
    TmrnaTagEntry::new("Desulfovibrio magneticus", "ANDYDYALAA"),
    TmrnaTagEntry::new("Desulfovibrio salexigens", "ANDNYDYAMAA"),
    TmrnaTagEntry::new("Desulfovibrio vulgaris", "ANNYDYALAA"),
    TmrnaTagEntry::new("Desulfovibrio yellowstonii", "ANNELALAA"),
    TmrnaTagEntry::new("Desulfurispirillum indicum", "ANDENVLAAA"),
    TmrnaTagEntry::new("Desulfurivibrio alkaliphilus", "ADDYAYAAAA"),
    TmrnaTagEntry::new("Desulfurobacterium thermolithotrophum", "ANEELALAA"),
    TmrnaTagEntry::new("Desulfuromonas acetoxidans", "ADTDVSYALAA"),
    TmrnaTagEntry::new("Dichelobacter nodosus", "ANDDNYALAA"),
    TmrnaTagEntry::new("Dickeya dadantii", "ANDENFAPAALAA"),
    TmrnaTagEntry::new("Dickeya zeae", "ANDENFAPAALAA"),
    TmrnaTagEntry::new("Dictyoglomus thermophilum", "ANTNLALAA"),
    TmrnaTagEntry::new("Dictyoglomus turgidum", "ANTNLALAA"),
    TmrnaTagEntry::new("Dinoroseobacter shibae", "ANDNRAPVAVAA"),
    TmrnaTagEntry::new("Dyadobacter fermentans", "GESTYAMAA"),
    TmrnaTagEntry::new("Edwardsiella tarda", "ANDENYALAA"),
    TmrnaTagEntry::new("Eggerthella lenta", "GKNNTQSAPALAMAA"),
    TmrnaTagEntry::new("Eggerthella sp. YY7918", "GKNNTQSAPALAMAA"),
    TmrnaTagEntry::new("Ehrlichia canis", "ANDNFVFANDNNSSVAGLVAA"),
    TmrnaTagEntry::new("Ehrlichia chaffeensis", "ANDNFVFANDNNSSANLVAA"),
    TmrnaTagEntry::new("Ehrlichia ruminantium 1", "ANDNFVSANDNNSTANLVAA"),
    TmrnaTagEntry::new("Ehrlichia ruminantium 2", "ANDNFVSANDNNSTANLVAA"),
    TmrnaTagEntry::new("Elusimicrobium minutum", "GNQTELNWATA"),
    TmrnaTagEntry::new("Emiliania huxleyi chloroplast", "ANNILNFNSKLAIA"),
    TmrnaTagEntry::new("Emticicia oligotrophica", "GNTSYAMAA"),
    TmrnaTagEntry::new("Enterobacter aerogenes", "ANDENYALAA"),
    TmrnaTagEntry::new("Enterobacter cancerogenus", "ANDENYALAA"),
    TmrnaTagEntry::new("Enterobacter cloacae", "ANDENYALAA"),
    TmrnaTagEntry::new("Enterobacter lignolyticus", "ANDENYALAA"),
    TmrnaTagEntry::new("Enterobacter sakazakii", "ANDENYALAA"),
    TmrnaTagEntry::new("Enterobacter sp. 638", "ANDENYALAA"),
    TmrnaTagEntry::new("Enterococcus durans", "AKNENNSYALAA"),
    TmrnaTagEntry::new("Enterococcus faecalis", "AKNENNSFALAA"),
    TmrnaTagEntry::new("Enterococcus faecium", "AKNENNSYALAA"),
    TmrnaTagEntry::new("Enterococcus hirae", "AKNENNSYALAA"),
    TmrnaTagEntry::new("Erwinia amylovora", "ANDENFAPAALAA"),
    TmrnaTagEntry::new("Erwinia billingiae", "ANDENYALAA"),
    TmrnaTagEntry::new("Erwinia carotovora", "ANDENYALAA"),
    TmrnaTagEntry::new("Erwinia chrysanthemi", "ANDENFAPAALAA"),
    TmrnaTagEntry::new("Erwinia pyrifoliae", "AKLKYNESVANDGEYELIAAAA"),
    TmrnaTagEntry::new("Erwinia sp. Ejp617", "AKLYNNIPVANDGEFITPALAA"),
    TmrnaTagEntry::new("Erwinia tasmaniensis", "ANDENFAPAALAA"),
    TmrnaTagEntry::new("Erysipelothrix rhusiopathiae", "GNNSLQFAA"),
    TmrnaTagEntry::new("Erythrobacter litoralis", "ANDNEALALAA"),
    TmrnaTagEntry::new("Escherichia coli", "ANDENYALAA"),
    TmrnaTagEntry::new("Ethanoligenens harbinense", "AKDNVIRVNFGRSEEALAA"),
    TmrnaTagEntry::new("Eubacterium eligens", "ANDNLAYAA"),
    TmrnaTagEntry::new("Eubacterium limosum", "AKENRSYGMALAA"),
    TmrnaTagEntry::new("Eubacterium rectale", "AEDNLAYAA"),
    TmrnaTagEntry::new("Exiguobacterium sibiricum", "GKTNTQLAAA"),
    TmrnaTagEntry::new("Exiguobacterium sp. AT1b", "GKTNTQLAAA"),
    TmrnaTagEntry::new("Ferrimonas balearica", "ANDENYALAA"),
    TmrnaTagEntry::new("Fervidobacterium nodosum", "ANEYVPLAA"),
    TmrnaTagEntry::new("Fervidobacterium pennivorans", "ANEYVPLAA"),
    TmrnaTagEntry::new("Fibrobacter succinogenes", "ADENYALAA"),
    TmrnaTagEntry::new("Filifactor alocis", "ANENNLLAA"),
    TmrnaTagEntry::new("Finegoldia magna", "AEDNNFALAA"),
    TmrnaTagEntry::new("Flavobacteriaceae bacterium", "GDQEFALAA"),
    TmrnaTagEntry::new("Flavobacterium columnare", "GENNYALAA"),
    TmrnaTagEntry::new("Flavobacterium indicum", "GENNYALAA"),
    TmrnaTagEntry::new("Flavobacterium johnsoniae", "GENNYALAA"),
    TmrnaTagEntry::new("Flexibacter litoralis", "GESNYAMAA"),
    TmrnaTagEntry::new("Flexistipes sinusarabici", "ANDEFALAAA"),
    TmrnaTagEntry::new("Fluviicola taffensis", "DNTSYALAA"),
    TmrnaTagEntry::new("Francisella cf.", "ANDSNFAAVAKAA"),
    TmrnaTagEntry::new("Francisella noatunensis", "ANDSNFAAVTKAA"),
    TmrnaTagEntry::new("Francisella novicida", "ANDSNFAAVAKAA"),
    TmrnaTagEntry::new("Francisella philomiragia", "ANDSNFAAVAKAA"),
    TmrnaTagEntry::new("Francisella sp. TX077308", "ANDSNFAAVAKAA"),
    TmrnaTagEntry::new("Francisella tularensis 1", "GNKKANRVAANDSNFAAVAKAA"),
    TmrnaTagEntry::new("Francisella tularensis 2", "ANDSNFAAVAKAA"),
    TmrnaTagEntry::new("Frankia alni", "ANKTQPVTPLYALAA"),
    TmrnaTagEntry::new("Frankia sp. CcI3", "ANKTQPTTPTYALAA"),
    TmrnaTagEntry::new("Frankia sp. EAN1pec", "ATKTQPASSTFALAA"),
    TmrnaTagEntry::new("Frankia sp. EuI1c", "ANSEQSATSAYALAA"),
    TmrnaTagEntry::new("Frankia symbiont", "ANKSQSATPRTFALAA"),
    TmrnaTagEntry::new("Frateuria aurantia", "ANDDNYALAA"),
    TmrnaTagEntry::new("Fremyella diplosiphon", "ANNIVKFARKEALVAA"),
    TmrnaTagEntry::new("Fusobacterium nucleatum 1", "GNKDYALAA"),
    TmrnaTagEntry::new("Fusobacterium nucleatum 2", "GNKEYALAA"),
    TmrnaTagEntry::new("Gallibacterium anatis", "ANDENYALAA"),
    TmrnaTagEntry::new("Gallionella capsiferriformans", "ANDENYALAA"),
    TmrnaTagEntry::new("gamma proteobacterium", "ANDESYALAA"),
    TmrnaTagEntry::new("Gammaproteobacteria SAR-1", "ANNYNYSLAA"),
    TmrnaTagEntry::new("Gardnerella vaginalis", "AKSNRTEFALAA"),
    TmrnaTagEntry::new("Gemmata obscuriglobus", "AEPQYSLAA"),
    TmrnaTagEntry::new("Gemmatimonas aurantiaca", "ANNNLALAA"),
    TmrnaTagEntry::new("Geobacillus kaustophilus", "GKQNYALAA"),
    TmrnaTagEntry::new("Geobacillus sp. WCH70", "GKENYALAA"),
    TmrnaTagEntry::new("Geobacillus sp. Y4.1MC1", "GKENYALAA"),
    TmrnaTagEntry::new("Geobacillus stearothermophilus", "GKQNYALAA"),
    TmrnaTagEntry::new("Geobacillus thermodenitrificans", "GKENYALAA"),
    TmrnaTagEntry::new("Geobacter bemidjiensis", "ADNYDYALAA"),
    TmrnaTagEntry::new("Geobacter daltonii", "ADNYDYALAA"),
    TmrnaTagEntry::new("Geobacter lovleyi", "ADNYNTQPVALAA"),
    TmrnaTagEntry::new("Geobacter metallireducens", "ADNYDYAVAA"),
    TmrnaTagEntry::new("Geobacter sp. M18", "ADNYDYALAA"),
    TmrnaTagEntry::new("Geobacter sp. M21", "ADNYDYALAA"),
    TmrnaTagEntry::new("Geobacter sulfurreducens", "ADNYDYAVAA"),
    TmrnaTagEntry::new("Geobacter uraniireducens", "ADNYNYALAA"),
    TmrnaTagEntry::new("Geodermatophilus obscurus", "ADSSQREFALAA"),
    TmrnaTagEntry::new("Glaciecola nitratireducens", "ANDENYALAA"),
    TmrnaTagEntry::new("Glaciecola sp. 4H-3-7+YE-5", "ANDENYALAA"),
    TmrnaTagEntry::new("Gloeobacter violaceus", "ATNNVVPFARARATVAA"),
    TmrnaTagEntry::new("Gluconacetobacter diazotrophicus", "ANDNSEVLAVAA"),
    TmrnaTagEntry::new("Gluconacetobacter xylinus", "ANDNSEVLAVAA"),
    TmrnaTagEntry::new("Gluconobacter oxydans", "ANDNSEVLAVAA"),
    TmrnaTagEntry::new("Gordonia bronchialis", "ADSNQRDYALAA"),
    TmrnaTagEntry::new("Gordonia polyisoprenivorans", "ADKNQRDYALAA"),
    TmrnaTagEntry::new("Gordonia rubripertincta", "ADSNQRDYALAA"),
    TmrnaTagEntry::new("Gordonia sp. KTR9", "ADSNQRDYALAA"),
    TmrnaTagEntry::new("Gracilaria tenuistipitata chloroplast", "AKNNILTLSRRLIYA"),
    TmrnaTagEntry::new("Gramella forsetii", "GENNYALAA"),
    TmrnaTagEntry::new("Granulibacter bethesdensis", "ANDNHEALAVAA"),
    TmrnaTagEntry::new("Granulicella mallensis", "AEPQFALAA"),
    TmrnaTagEntry::new("Granulicella tundricola", "AEPQFALAA"),
    TmrnaTagEntry::new("Guillardia theta chloroplast", "ASNIVSFSSKRLVSFA"),
    TmrnaTagEntry::new("Haemophilus ducreyi", "ANDEQYALAA"),
    TmrnaTagEntry::new("Haemophilus influenzae", "ANDEQYALAA"),
    TmrnaTagEntry::new("Haemophilus parainfluenzae", "ANDEQYALAA"),
    TmrnaTagEntry::new("Haemophilus parasuis", "ANDEQYALAA"),
    TmrnaTagEntry::new("Haemophilus somnus", "ANDEQYALAA"),
    TmrnaTagEntry::new("Hahella chejuensis", "ANDETYALAA"),
    TmrnaTagEntry::new("Halanaerobium hydrogeniformans", "ANDNSYALAAA"),
    TmrnaTagEntry::new("Halanaerobium praevalens", "ANDNNYTLAAA"),
    TmrnaTagEntry::new("Haliangium ochraceum", "ANDNAVALAA"),
    TmrnaTagEntry::new("Haliscomenobacter hydrossis", "GESNYAMAA"),
    TmrnaTagEntry::new("Halobacillus halophilus", "GESNDNLAVAA"),
    TmrnaTagEntry::new("Halomonas elongata", "ANDDNYAQGALAA"),
    TmrnaTagEntry::new("Halorhodospira halophila", "ANDDNYALAA"),
    TmrnaTagEntry::new("Halothermothrix orenii", "ADNNNYALAAA"),
    TmrnaTagEntry::new("Halothiobacillus neapolitanus", "ANDDNYALAA"),
    TmrnaTagEntry::new("Hamiltonella defensa", "AKINKNRPAANGYMPVAALAA"),
    TmrnaTagEntry::new("Helicobacter acinonychis", "VNNTDYAPAYAKVA"),
    TmrnaTagEntry::new("Helicobacter bizzozeronii", "VNNPNYAPNYAKAA"),
    TmrnaTagEntry::new("Helicobacter cetorum", "VNNTNYAPAYAKVA"),
    TmrnaTagEntry::new("Helicobacter cinaedi", "ANNTNYAPVYAKVA"),
    TmrnaTagEntry::new("Helicobacter felis", "VNNPNYAPNYAKAA"),
    TmrnaTagEntry::new("Helicobacter hepaticus", "ANNANYAPAYAKVA"),
    TmrnaTagEntry::new("Helicobacter mustelae", "ANNKNYAPAYAKVA"),
    TmrnaTagEntry::new("Helicobacter pylori 1", "VNNTDYAPAYAKAA"),
    TmrnaTagEntry::new("Helicobacter pylori 2", "VNNTDYAPAYAKAA"),
    TmrnaTagEntry::new("Helicobacter pylori 3", "VNNADYAPAYAKAA"),
    TmrnaTagEntry::new("Heliobacillus mobilis", "AEDNYALAA"),
    TmrnaTagEntry::new("Heliobacterium modesticaldum", "AEENYALAA"),
    TmrnaTagEntry::new("Herbaspirillum seropedicae", "ANDESYALAA"),
    TmrnaTagEntry::new("Herminiimonas arsenicoxydans", "DNSYALAA"),
    TmrnaTagEntry::new("Herpetosiphon aurantiacus", "GKNTFRAPVALAA"),
    TmrnaTagEntry::new("Hippea maritima", "ADTEYALAA"),
    TmrnaTagEntry::new("Hirschia baltica", "ANDNFAEGELLAA"),
    TmrnaTagEntry::new("Hydrogenophaga palleronii", "ANDERFALAA"),
    TmrnaTagEntry::new("Hyphomicrobium denitrificans", "ANDNYAEAALAA"),
    TmrnaTagEntry::new("Hyphomicrobium sp. MC1", "ANDNYAEAALAA"),
    TmrnaTagEntry::new("Hyphomonas neptunium", "ANDNFAEGELLAA"),
    TmrnaTagEntry::new("Idiomarina loihiensis", "ANDDNYALAA"),
    TmrnaTagEntry::new("Ignavibacterium album", "GEYNYALAA"),
    TmrnaTagEntry::new("Ilyobacter polytropus", "ENNNYALAA"),
    TmrnaTagEntry::new("Intrasporangium calvum", "ANSKRTDFALAA"),
    TmrnaTagEntry::new("Isoptericola variabilis", "ADNKRTDFTLAA"),
    TmrnaTagEntry::new("Jannaschia sp. CCS1", "ANDNRAPAMALAA"),
    TmrnaTagEntry::new("Janthinobacterium sp. Marseille", "ANDNSYALAA"),
    TmrnaTagEntry::new("Jonesia denitrificans", "ADTKRTDFALAA"),
    TmrnaTagEntry::new("Kangiella koreensis", "ANEDNYALAA"),
    TmrnaTagEntry::new("Ketogulonicigenium vulgare", "ANNNRAPAMALAA"),
    TmrnaTagEntry::new("Kineococcus radiotolerans", "ADSKRTEFALAA"),
    TmrnaTagEntry::new("Kitasatospora setae", "ANSKRDSQQFALAA"),
    TmrnaTagEntry::new("Klebsiella oxytoca", "ANDENYALAA"),
    TmrnaTagEntry::new("Klebsiella pneumoniae", "ANDENYALAA"),
    TmrnaTagEntry::new("Kocuria rhizophila", "AKSKRTDFALAA"),
    TmrnaTagEntry::new("Koribacter versatilis", "ANTQMAYAA"),
    TmrnaTagEntry::new("Kosmotoga olearia", "ANTEFALAA"),
    TmrnaTagEntry::new("Kribbella flavida", "ADSKRSSFALAA"),
    TmrnaTagEntry::new("Krokinobacter sp. 4H-3-7-5", "GENNYALAA"),
    TmrnaTagEntry::new("Kyrpidia tusciae", "ANKQELALAA"),
    TmrnaTagEntry::new("Kytococcus sedentarius", "ANSKRTDFALAA"),
    TmrnaTagEntry::new("Lacinutrix sp. 5H-3-7-4", "GENNYALAA"),
    TmrnaTagEntry::new("Lactobacillus acidophilus", "ANNKNSYALAA"),
    TmrnaTagEntry::new("Lactobacillus amylovorus", "ANNKNSYALAA"),
    TmrnaTagEntry::new("Lactobacillus brevis", "AKNNNNSYALAA"),
    TmrnaTagEntry::new("Lactobacillus buchneri", "AKNNNNSYALAA"),
    TmrnaTagEntry::new("Lactobacillus casei", "AKNENSYALAA"),
    TmrnaTagEntry::new("Lactobacillus crispatus", "ANNKNSYALAA"),
    TmrnaTagEntry::new("Lactobacillus delbrueckii 1", "AKNENNSYALAA"),
    TmrnaTagEntry::new("Lactobacillus delbrueckii 2", "ANENSYAVAA"),
    TmrnaTagEntry::new("Lactobacillus fermentum", "ANNNSQSYAYAA"),
    TmrnaTagEntry::new("Lactobacillus gallinarum", "ANNKNSYALAA"),
    TmrnaTagEntry::new("Lactobacillus gasseri", "ANNENSYAVAA"),
    TmrnaTagEntry::new("Lactobacillus helveticus", "ANNKNSYALAA"),
    TmrnaTagEntry::new("Lactobacillus johnsonii", "ANNENSYAVAA"),
    TmrnaTagEntry::new("Lactobacillus kefiranofaciens", "ANNKNSYALAA"),
    TmrnaTagEntry::new("Lactobacillus plantarum", "AKNNNNSYALAA"),
    TmrnaTagEntry::new("Lactobacillus reuteri", "ANNNSNSYAYAA"),
    TmrnaTagEntry::new("Lactobacillus rhamnosus", "AKNENSYALAA"),
    TmrnaTagEntry::new("Lactobacillus ruminis", "AKNNNYSYALAA"),
    TmrnaTagEntry::new("Lactobacillus sakei", "ANNNNSYAVAA"),
    TmrnaTagEntry::new("Lactobacillus salivarius", "AKNNNNSYALAA"),
    TmrnaTagEntry::new("Lactobacillus sanfranciscensis", "AKNNNNSYALAA"),
    TmrnaTagEntry::new("Lactococcus garvieae", "AKNNTSYALAA"),
    TmrnaTagEntry::new("Lactococcus lactis", "AKNNTQTYAMAA"),
    TmrnaTagEntry::new("Lactococcus plantarum", "AKNTQTYALAA"),
    TmrnaTagEntry::new("Lactococcus raffinolactis", "AKNTQTYAVAA"),
    TmrnaTagEntry::new("Laribacter hongkongensis", "ANDDTYALAA"),
    TmrnaTagEntry::new("Lawsonia intracellularis", "ANNNYDYALAA"),
    TmrnaTagEntry::new("Leadbetterella byssophila", "GNTSYAMAA"),
    TmrnaTagEntry::new("Legionella longbeachae", "ANDENFAGGEAIAA"),
    TmrnaTagEntry::new("Legionella pneumophila", "ANDENFAGGEAIAA"),
    TmrnaTagEntry::new("Leifsonia xyli", "ANSKSTVSAKADFALAA"),
    TmrnaTagEntry::new("Leptolyngbya boryana", "ANNIVPFARKTAPVAA"),
    TmrnaTagEntry::new("Leptospira biflexa", "ANNEFALAA"),
    TmrnaTagEntry::new("Leptospira borgpetersenii", "ANNELALAA"),
    TmrnaTagEntry::new("Leptospira interrogans", "ANNELALAA"),
    TmrnaTagEntry::new("Leptospirillum ferriphilum", "ANEELALAA"),
    TmrnaTagEntry::new("Leptospirillum ferrooxidans", "ANNEMALAA"),
    TmrnaTagEntry::new("Leptospirillum groupII", "ANEELALAA"),
    TmrnaTagEntry::new("Leptospirillum groupIII", "ANEELALAA"),
    TmrnaTagEntry::new("Leptospirillum sp. Group II '5-way CG'", "ANEELALAA"),
    TmrnaTagEntry::new("Leptospirillum sp. Group III", "ANEELALAA"),
    TmrnaTagEntry::new("Leptothrix cholodnii", "ANDSTYALAA"),
    TmrnaTagEntry::new("Leptotrichia buccalis", "GNDNYALAA"),
    TmrnaTagEntry::new("Leuconostoc carnosum", "AKNENTFAVAA"),
    TmrnaTagEntry::new("Leuconostoc citreum", "AKNENSFAIAA"),
    TmrnaTagEntry::new("Leuconostoc gasicomitatum", "AKNENSFAIAA"),
    TmrnaTagEntry::new("Leuconostoc gelidum", "AKNENSFAIAA"),
    TmrnaTagEntry::new("Leuconostoc lactis", "AKNENSFAIAA"),
    TmrnaTagEntry::new("Leuconostoc mesenteroides", "AKNENSFAIAA"),
    TmrnaTagEntry::new("Leuconostoc pseudomesenteroides", "AKNENSYAIAA"),
    TmrnaTagEntry::new("Leuconostoc sp. C2", "AKNENSFAIAA"),
    TmrnaTagEntry::new("Liberibacter asiaticus", "ANDNSAREVLAA"),
    TmrnaTagEntry::new("Liberibacter solanacearum", "ANDNFAGETRLAA"),
    TmrnaTagEntry::new("Listeria grayi 1", "GKEKQNLAFAA"),
    TmrnaTagEntry::new("Listeria grayi 2", "GKQNNNLAFAA"),
    TmrnaTagEntry::new("Listeria innocua", "GKEKQNLAFAA"),
    TmrnaTagEntry::new("Listeria ivanovii", "GKEKQNLAFAA"),
    TmrnaTagEntry::new("Listeria monocytogenes", "GKEKQNLAFAA"),
    TmrnaTagEntry::new("Listeria seeligeri", "GKEKQNLAFAA"),
    TmrnaTagEntry::new("Listeria welshimeri", "GKEKQNLAFAA"),
    TmrnaTagEntry::new("Lysinibacillus sphaericus", "GKQQNLAFAA"),
    TmrnaTagEntry::new("Macrococcus caseolyticus", "GKTNNFAVAA"),
    TmrnaTagEntry::new("Magnetococcus marinus", "ANDEHYAPAFAAA"),
    TmrnaTagEntry::new("Magnetococcus sp.", "ANDEHYAPAFAAA"),
    TmrnaTagEntry::new("Magnetospirillum magneticum", "ANDNVELAAAA"),
    TmrnaTagEntry::new("Magnetospirillum magnetotacticum 1", "ANDNFAPVAVAA"),
    TmrnaTagEntry::new("Magnetospirillum magnetotacticum 2", "ANDNVELAAAA"),
    TmrnaTagEntry::new("Mahella australiensis", "ADNNAELALAA"),
    TmrnaTagEntry::new("Mannheimia haemolytica", "ANDEQYALAA"),
    TmrnaTagEntry::new("Mannheimia succiniciproducens", "ANDEQYALAA"),
    TmrnaTagEntry::new("Maribacter sp. HTCC2170", "GDNNYALAA"),
    TmrnaTagEntry::new("Maricaulis maris", "ANDNFAEEVALAA"),
    TmrnaTagEntry::new("Marinithermus hydrothermalis", "GNNRYALAA"),
    TmrnaTagEntry::new("Marinitoga piezophila", "AEENYALAA"),
    TmrnaTagEntry::new("Marinobacter adhaerens", "ANDENYALAA"),
    TmrnaTagEntry::new("Marinobacter aquaeolei", "ANDENYALAA"),
    TmrnaTagEntry::new("Marinobacter hydrocarbonoclasticus", "ANDENYALAA"),
    TmrnaTagEntry::new("Marinobacter sp. BSs20148", "ANDENYSLAA"),
    TmrnaTagEntry::new("Marinomonas mediterranea", "ANDENYALAA"),
    TmrnaTagEntry::new("Marinomonas posidonica", "ANDENYALAA"),
    TmrnaTagEntry::new("Marinomonas sp. MWYL1", "ANDENYALAA"),
    TmrnaTagEntry::new("Marivirga tractuosa", "GESNYAMAA"),
    TmrnaTagEntry::new("Megasphaera elsdenii", "AKENNFALAA"),
    TmrnaTagEntry::new("Meiothermus ruber", "GNVRSNSYALAA"),
    TmrnaTagEntry::new("Meiothermus silvanus", "GNTQRSYALAA"),
    TmrnaTagEntry::new("Melioribacter roseus", "GEYNYALAA"),
    TmrnaTagEntry::new("Melissococcus plutonius", "AKKQNYSYAVAA"),
    TmrnaTagEntry::new("Mesoplasma florum", "ANKNEENTNEVPTFMLNAGQANYAFA"),
    TmrnaTagEntry::new("Mesorhizobium ciceri", "ANDNYAEARLAA"),
    TmrnaTagEntry::new("Mesorhizobium loti", "ANDNYAEARLAA"),
    TmrnaTagEntry::new("Mesorhizobium opportunistum", "ANDNYAEARLAA"),
    TmrnaTagEntry::new("Mesorhizobium sp.", "ANDNYAEARLAA"),
    TmrnaTagEntry::new("Mesostigma viride chloroplast", "ANNILPFNRKTAVAV"),
    TmrnaTagEntry::new("Mesotoga prima", "ANNEFALAA"),
    TmrnaTagEntry::new("Methylacidiphilum infernorum", "ANEELALAA"),
    TmrnaTagEntry::new("Methylibium petroleiphilum", "ANDERFALAA"),
    TmrnaTagEntry::new("Methylobacillus flagellatus", "ANDETYALAA"),
    TmrnaTagEntry::new("Methylobacillus glycogenes", "ANDETYALAA"),
    TmrnaTagEntry::new("Methylobacterium extorquens", "ANDNFAPVAVAA"),
    TmrnaTagEntry::new("Methylobacterium nodulans", "ANDNYAPVAVAA"),
    TmrnaTagEntry::new("Methylobacterium populi", "ANDNFAPVAVAA"),
    TmrnaTagEntry::new("Methylobacterium radiotolerans", "ANDNFAPVAVAA"),
    TmrnaTagEntry::new("Methylobacterium sp. 4-46", "ANDNYAPVAVAA"),
    TmrnaTagEntry::new("Methylocella silvestris", "ANDNYAPVAVAA"),
    TmrnaTagEntry::new("Methylococcus capsulatus", "ANDDVYALAA"),
    TmrnaTagEntry::new("Methylocystis sp. SC2", "ANDNYAPVAVAA"),
    TmrnaTagEntry::new("Methylomicrobium alcaliphilum", "ANDENYSMALAA"),
    TmrnaTagEntry::new("Methylomirabilis oxyfera", "ANHELALAA"),
    TmrnaTagEntry::new("Methylomonas methanica", "ANDENYSVALAA"),
    TmrnaTagEntry::new("Methylophaga sp. JAM1", "ANDNNYALAA"),
    TmrnaTagEntry::new("Methylophaga sp. JAM7", "ANDNNYALAA"),
    TmrnaTagEntry::new("Methylotenera mobilis", "ANDETYSLAA"),
    TmrnaTagEntry::new("Methylotenera versatilis", "ANDETYSLAA"),
    TmrnaTagEntry::new("Methylovorus glucosetrophus", "ANDETYALAA"),
    TmrnaTagEntry::new("Micavibrio aeruginosavorus", "ANDNFVVANDNSREAAVAIAA"),
    TmrnaTagEntry::new("Microbacterium testaceum", "ADAKRTDFALAA"),
    TmrnaTagEntry::new("Microbulbifer degradans", "ANDDNYGAQLAA"),
    TmrnaTagEntry::new("Micrococcus luteus", "AESKRTDFALAA"),
    TmrnaTagEntry::new("Microcystis aeruginosa", "ANNIVPFARKAAPVAA"),
    TmrnaTagEntry::new("Microlunatus phosphovorus", "AKSEQRTDFALAA"),
    TmrnaTagEntry::new("Micromonospora aurantiaca", "AKNNRADFALAA"),
    TmrnaTagEntry::new("Midichloria mitochondrii", "ANNKFVPANSDFVPALQAA"),
    TmrnaTagEntry::new("Mobiluncus curtisii", "AERNSTESFALAA"),
    TmrnaTagEntry::new("Modestobacter marinus", "ADSSQRDFALAA"),
    TmrnaTagEntry::new("Moorella thermoacetica", "ADDNLALAA"),
    TmrnaTagEntry::new("Moranella endobia", "ANDSQYESVALAA"),
    TmrnaTagEntry::new("Moraxella catarrhalis", "ANDETYALAA"),
    TmrnaTagEntry::new("Muricauda ruestringensis", "GENNYALAA"),
    TmrnaTagEntry::new("Mycobacteriophage Bxz1 virion", "ATDTDATVTDAEIEAFFAEEAAALV"),
    TmrnaTagEntry::new("Mycobacterium abscessus", "ADSHQRDYALAA"),
    TmrnaTagEntry::new("Mycobacterium africanum", "ADSHQRDYALAA"),
    TmrnaTagEntry::new("Mycobacterium austroafricanum", "ADSNQRDYALAA"),
    TmrnaTagEntry::new("Mycobacterium avium", "ADSHQRDYALAA"),
    TmrnaTagEntry::new("Mycobacterium bovis", "ADSHQRDYALAA"),
    TmrnaTagEntry::new("Mycobacterium chubuense", "ADSNQRDYALAA"),
    TmrnaTagEntry::new("Mycobacterium gilvum", "ADSNQRDYALAA"),
    TmrnaTagEntry::new("Mycobacterium indicus", "ADSHQRDYALAA"),
    TmrnaTagEntry::new("Mycobacterium intracellulare", "ADSHQRDYALAA"),
    TmrnaTagEntry::new("Mycobacterium leprae", "ADSYQRDYALAA"),
    TmrnaTagEntry::new("Mycobacterium marinum", "ADSHQRDYALAA"),
    TmrnaTagEntry::new("Mycobacterium microti", "ADSHQRDYALAA"),
    TmrnaTagEntry::new("Mycobacterium phage", "ATDTDATVTDAEIEAFFAEEAAALV"),
    TmrnaTagEntry::new("Mycobacterium rhodesiae", "ADSNQRDFALAA"),
    TmrnaTagEntry::new("Mycobacterium smegmatis", "ADSNQRDYALAA"),
    TmrnaTagEntry::new("Mycobacterium sp. MCS", "ADTNQRDYALAA"),
    TmrnaTagEntry::new("Mycobacterium tuberculosis", "ADSHQRDYALAA"),
    TmrnaTagEntry::new("Mycoplasma agalactiae", "ANDKKSEEVRVELPAFAIANANANLAFA"),
    TmrnaTagEntry::new("Mycoplasma arthritidis", "GNLETSEDKKLDLQFVMNSQTQQNLLFA"),
    TmrnaTagEntry::new("Mycoplasma bovis", "ANDKKSEEVRLELPAFAIANANANLAFA"),
    TmrnaTagEntry::new("Mycoplasma capricolum", "ANKNEETFEMPAFMMNNASAGANFMFA"),
    TmrnaTagEntry::new("Mycoplasma conjunctivae", "ANKKEDKAVDVNLLASQSFNSNLAFA"),
    TmrnaTagEntry::new("Mycoplasma crocodyli", "GKSKKAENEFSFSNPAFAGNLNLAFA"),
    TmrnaTagEntry::new("Mycoplasma fermentans", "AEDKKAEEVNISSLMIAQKMQSQSNLAFA"),
    TmrnaTagEntry::new("Mycoplasma gallisepticum", "DKTSKELADENFVLNQLASNNYALNF"),
    TmrnaTagEntry::new("Mycoplasma genitalium 1", "DKENNEVLVEPNLIINQQASVNFAFA"),
    TmrnaTagEntry::new("Mycoplasma genitalium 2", "DKENNEVLVDPNLIINQQASVNFAFA"),
    TmrnaTagEntry::new("Mycoplasma haemofelis", "ANKQERESSVVNLLMSQPQDLASLSF"),
    TmrnaTagEntry::new("Mycoplasma hominis", "AEEKQNKQSFVLNQMMSSNPVFAY"),
    TmrnaTagEntry::new("Mycoplasma hyorhinis", "GKENKKEDYSLLMNASTQSNLAFAF"),
    TmrnaTagEntry::new("Mycoplasma leachii", "ANKNEETFEMPAFMMNNASAGANFMFA"),
    TmrnaTagEntry::new("Mycoplasma mobile", "GKEKQLEVSPLLMSSSQSNLVFA"),
    TmrnaTagEntry::new("Mycoplasma mycoides", "ADKNEENFEMPAFMINNASAGANYMFA"),
    TmrnaTagEntry::new("Mycoplasma penetrans", "AKNNKNEAVEVELNDFEINALSQNANLALYA"),
    TmrnaTagEntry::new("Mycoplasma pneumoniae", "DKNNDEVLVDPMLIANQQASINYAFA"),
    TmrnaTagEntry::new("Mycoplasma pulmonis", "GTKKQENDYQDLMISQNLNQNLAFASV"),
    TmrnaTagEntry::new("Mycoplasma putrefaciens", "ANKKTEEFEMPAFMINNASAGANLMFA"),
    TmrnaTagEntry::new("Mycoplasma synoviae", "GNKQSQVEEVTREFSPSLYTFNSNLAYA"),
    TmrnaTagEntry::new("Myxococcus fulvus", "ANDNVELALAA"),
    TmrnaTagEntry::new("Myxococcus xanthus", "ANDNVELALAA"),
    TmrnaTagEntry::new("Nakamurella multipartita", "ADSKRTEFALAA"),
    TmrnaTagEntry::new("Natranaerobius thermophilus", "ADEDYALAAA"),
    TmrnaTagEntry::new("Nautilia profundicola", "AANNTNYSPAVARAAA"),
    TmrnaTagEntry::new("Neisseria gonorrhoeae", "ANDETYALAA"),
    TmrnaTagEntry::new("Neisseria lactamica", "ANDETYALAA"),
    TmrnaTagEntry::new("Neisseria meningitidis", "ANDETYALAA"),
    TmrnaTagEntry::new("Nephroselmis olivacea chloroplast", "TTYHSCLEGHLS"),
    TmrnaTagEntry::new("Niastella koreensis", "GNTQFAMAA"),
    TmrnaTagEntry::new("Nitratifractor salsuginis", "ANNTDYRPAYAHAA"),
    TmrnaTagEntry::new("Nitratiruptor sp. SB155-2", "ANNTDYRPAYAVAA"),
    TmrnaTagEntry::new("Nitrobacter hamburgensis", "ANDNYAPVAQAA"),
    TmrnaTagEntry::new("Nitrobacter Nb-311A", "ANDNYAPVAQAA"),
    TmrnaTagEntry::new("Nitrobacter winogradskyi", "ANDNYAPVAQAA"),
    TmrnaTagEntry::new("Nitrosococcus halophilus", "ANDDNYALAA"),
    TmrnaTagEntry::new("Nitrosococcus oceani", "ANDDNYALAA"),
    TmrnaTagEntry::new("Nitrosococcus watsonii", "ANDDNYALAA"),
    TmrnaTagEntry::new("Nitrosomonas cryotolerans", "ANDENYALAA"),
    TmrnaTagEntry::new("Nitrosomonas europaea", "ANDENYALAA"),
    TmrnaTagEntry::new("Nitrosomonas eutropha", "ANDENYALAA"),
    TmrnaTagEntry::new("Nitrosomonas sp. AL212", "ANDENYALAA"),
    TmrnaTagEntry::new("Nitrosomonas sp. Is79A3", "ANDENYALAA"),
    TmrnaTagEntry::new("Nitrosospira multiformis", "ANDENYALAA"),
    TmrnaTagEntry::new("Nitrospira defluvii", "ANQELALAA"),
    TmrnaTagEntry::new("Nocardia brasiliensis", "ADSNQREYALAA"),
    TmrnaTagEntry::new("Nocardia cyriacigeorgica", "ADSHQREYALAA"),
    TmrnaTagEntry::new("Nocardia farcinica", "ADSHQREYALAA"),
    TmrnaTagEntry::new("Nocardioides sp. JS614", "ANTNRSSFALAA"),
    TmrnaTagEntry::new("Nocardiopsis alba", "ANSKRTEFALAA"),
    TmrnaTagEntry::new("Nocardiopsis dassonvillei", "ANSKRTEFALAA"),
    TmrnaTagEntry::new("Nostoc azollae", "ANNIVKFARREALVAA"),
    TmrnaTagEntry::new("Nostoc PCC7120", "ANNIVKFARKDALVAA"),
    TmrnaTagEntry::new("Nostoc punctiforme", "ANNIVNFARKDALVAA"),
    TmrnaTagEntry::new("Nostoc sp. PCC 7120", "ANNIVKFARKDALVAA"),
    TmrnaTagEntry::new("Novosphingobium aromaticivorans", "ANDNEALALAA"),
    TmrnaTagEntry::new("Novosphingobium sp. PP1Y", "ANDNEALALAA"),
    TmrnaTagEntry::new("Oceanimonas sp. GK1", "ANDENYALAA"),
    TmrnaTagEntry::new("Oceanithermus profundus", "GNDNYALAA"),
    TmrnaTagEntry::new("Oceanobacillus iheyensis", "GKETNQPVLAAA"),
    TmrnaTagEntry::new("Ochrobactrum anthropi", "ANDNKAQGYALAA"),
    TmrnaTagEntry::new("Odontella sinensis chloroplast", "ANNLISSVFKSLSTKQNSLNLSFAV"),
    TmrnaTagEntry::new("Odoribacter splanchnicus", "GENNYALAA"),
    TmrnaTagEntry::new("Oenococcus oeni", "AKNNEPSYALAA"),
    TmrnaTagEntry::new("Oligotropha carboxidovorans", "ANDNYAPVAQAA"),
    TmrnaTagEntry::new("Olsenella uli", "DNDSYQGSYALAA"),
    TmrnaTagEntry::new("Ornithobacterium rhinotracheale", "GNNEYALAA"),
    TmrnaTagEntry::new("Oscillatoria 6304", "ANNIVPFARKAAPVAA"),
    TmrnaTagEntry::new("Oscillatoria acuminata", "ANNIVPFARKAAPVAA"),
    TmrnaTagEntry::new("Owenweeksia hongkongensis", "GENNFALAA"),
    TmrnaTagEntry::new("Paenibacillus larvae", "GKQQNNYALAA"),
    TmrnaTagEntry::new("Paenibacillus mucilaginosus", "GNQKQQLAFAA"),
    TmrnaTagEntry::new("Paenibacillus polymyxa", "GKQQNNYAFAA"),
    TmrnaTagEntry::new("Paenibacillus sp. JDR-2", "GKQQQTYAFAA"),
    TmrnaTagEntry::new("Paenibacillus sp. Y412MC10", "GKQQNNYAFAA"),
    TmrnaTagEntry::new("Paenibacillus terrae", "GKQQNNYAFAA"),
    TmrnaTagEntry::new("Paludibacter propionicigenes", "GENNYALAA"),
    TmrnaTagEntry::new("Pantoea ananatis", "ANDENYALAA"),
    TmrnaTagEntry::new("Pantoea sp. At-9b", "ANDNYYDAPAALAA"),
    TmrnaTagEntry::new("Pantoea stewartii", "ANDENYALAA"),
    TmrnaTagEntry::new("Pantoea vagans", "ANDENYALAA"),
    TmrnaTagEntry::new("Parabacteroides distasonis", "GENNYALAA"),
    TmrnaTagEntry::new("Parachlamydia acanthamoebae", "ADSVSYAAAA"),
    TmrnaTagEntry::new("Parachlamydia UWE25", "ANNSNKIAKVDFQEGTFARAA"),
    TmrnaTagEntry::new("Paracoccus denitrificans", "ANDNRAPVALAA"),
    TmrnaTagEntry::new("Parvibaculum lavamentivorans", "ANDNYAEARLAA"),
    TmrnaTagEntry::new("Parvularcula bermudensis", "ANDNSSEGFALAA"),
    TmrnaTagEntry::new("Pasteurella multocida", "ANDEQYALAA"),
    TmrnaTagEntry::new("Pavlova lutheri chloroplast", "ANNILSFNRVAVA"),
    TmrnaTagEntry::new("Pectobacterium atrosepticum", "ANDENYALAA"),
    TmrnaTagEntry::new("Pectobacterium carotovora", "ANDENYALAA"),
    TmrnaTagEntry::new("Pectobacterium carotovorum", "ANDENYALAA"),
    TmrnaTagEntry::new("Pectobacterium wasabiae", "ANDENYALAA"),
    TmrnaTagEntry::new("Pediococcus claussenii", "AKNNNNSYALAA"),
    TmrnaTagEntry::new("Pediococcus pentosaceus", "AKNNNNSYALAA"),
    TmrnaTagEntry::new("Pedobacter heparinus", "GENNYALAA"),
    TmrnaTagEntry::new("Pedobacter saltans", "ENNYALAA"),
    TmrnaTagEntry::new("Pelagibacter sp. IMCC9063", "ANESYAIAA"),
    TmrnaTagEntry::new("Pelagibacter ubique", "ADESYALAA"),
    TmrnaTagEntry::new("Pelagibacterium halotolerans", "ANDNNKAPVALAA"),
    TmrnaTagEntry::new("Pelobacter carbinolicus", "ADTDVSYALAA"),
    TmrnaTagEntry::new("Pelobacter propionicus", "ADNYNTPVALAA"),
    TmrnaTagEntry::new("Pelodictyon phaeoclathratiforme", "ADDYSYAMAA"),
    TmrnaTagEntry::new("Pelotomaculum thermopropionicum", "AKENYALAA"),
    TmrnaTagEntry::new("Petrotoga mobilis", "GGSSLPKFSWNLA"),
    TmrnaTagEntry::new("Phaeobacter gallaeciensis", "ANDNRAPAMAVAA"),
    TmrnaTagEntry::new("Photobacterium phosphoreum", "ANDENYALAA"),
    TmrnaTagEntry::new("Photobacterium profundum", "ANDENFALAA"),
    TmrnaTagEntry::new("Photorhabdus asymbiotica", "ANDNEYALVA"),
    TmrnaTagEntry::new("Photorhabdus luminescens", "ANDEKYALAA"),
    TmrnaTagEntry::new("Phycisphaera mikurensis", "ANDENTIAGRIGFGNDALRLAA"),
    TmrnaTagEntry::new("Phytoplasma australiense", "GKQTNSASEGDQIYNWVPSQSSQNLQQLAFA"),
    TmrnaTagEntry::new("Pirellula sp.", "AEENFALAA"),
    TmrnaTagEntry::new("Pirellula staleyi", "AESNLALAA"),
    TmrnaTagEntry::new("Planctomyces brasiliensis", "ANKQYAMVA"),
    TmrnaTagEntry::new("Planctomyces limnophilus", "ANTGNYALAA"),
    TmrnaTagEntry::new("Plectonema boryanum", "ANNIVPFARKTAPVAA"),
    TmrnaTagEntry::new("Polaromonas JS666", "ANDERFALAA"),
    TmrnaTagEntry::new("Polaromonas naphthalenivorans", "ANDERFALAA"),
    TmrnaTagEntry::new("Polaromonas sp. JS666", "ANDERFALAA"),
    TmrnaTagEntry::new("Polymorphum gilvum", "ANDNYASDVALAA"),
    TmrnaTagEntry::new("Polynucleobacter necessarius", "ANDERFALAA"),
    TmrnaTagEntry::new("Porphyra purpurea chloroplast", "AENNIIAFSRKLAVA"),
    TmrnaTagEntry::new("Porphyromonas asaccharolytica", "AETRHHPGGRCSEAL"),
    TmrnaTagEntry::new("Porphyromonas gingivalis", "GENNYALAA"),
    TmrnaTagEntry::new("Prevotella denticola", "GENNYALAA"),
    TmrnaTagEntry::new("Prevotella intermedia", "GENNYALAA"),
    TmrnaTagEntry::new("Prevotella melaninogenica", "GENNYALAA"),
    TmrnaTagEntry::new("Prevotella ruminicola", "GNNEYALAA"),
    TmrnaTagEntry::new("Prochlorococcus marinus 1", "ANKIVSFSRQTAPVAA"),
    TmrnaTagEntry::new("Prochlorococcus marinus 2", "ANNIVRFSRQPALVAA"),
    TmrnaTagEntry::new("Prochlorococcus marinus 3", "ANKIVSFSRQTAPVAA"),
    TmrnaTagEntry::new("Prochlorococcus marinus", "ANNIVSFSRQTAPVAA"),
    TmrnaTagEntry::new("Propionibacterium acidipropionici", "ADNKRTDFALAA"),
    TmrnaTagEntry::new("Propionibacterium acnes 1", "AENTRTDFALAA"),
    TmrnaTagEntry::new("Propionibacterium acnes 2", "AENTRTDFALAA"),
    TmrnaTagEntry::new("Propionibacterium freudenreichii", "ADTNRTDFALAA"),
    TmrnaTagEntry::new("Propionibacterium propionicum", "ANNSRTDFALAA"),
    TmrnaTagEntry::new("Prosthecochloris aestuarii", "ADDYSYAMAA"),
    TmrnaTagEntry::new("Proteobacteria SAR-1, version 1", "GENADYALAA"),
    TmrnaTagEntry::new("Proteobacteria SAR-1, version 2", "ANNYNYSLAA"),
    TmrnaTagEntry::new("Proteobacteria SAR-1, version 3", "ADNGYMAAA"),
    TmrnaTagEntry::new("Proteus mirabilis", "ANDNQYKALAA"),
    TmrnaTagEntry::new("Protochlamydia amoebophila", "ANNSNKIAKVDFQEGTFARAA"),
    TmrnaTagEntry::new("Providencia rettgeri", "ANDENYALAA"),
    TmrnaTagEntry::new("Providencia stuartii", "ANDENYALAA"),
    TmrnaTagEntry::new("Pseudoalteromonas atlantica", "ANDENYALAA"),
    TmrnaTagEntry::new("Pseudoalteromonas haloplanktis", "ANDDNYSLAA"),
    TmrnaTagEntry::new("Pseudoalteromonas sp. SM9913", "ANDDNYSLAA"),
    TmrnaTagEntry::new("Pseudogulbenkiania sp. NH8B", "ANDETYALAA"),
    TmrnaTagEntry::new("Pseudomonas aeruginosa", "ANDDNYALAA"),
    TmrnaTagEntry::new("Pseudomonas brassicacearum", "ANDENYGQEFAIAA"),
    TmrnaTagEntry::new("Pseudomonas chlororaphis", "ANDETYGEYALAA"),
    TmrnaTagEntry::new("Pseudomonas entomophila", "ANDENYEGYALAA"),
    TmrnaTagEntry::new("Pseudomonas fluorescens 1", "ANDDQYGAALAA"),
    TmrnaTagEntry::new("Pseudomonas fluorescens 2", "ANDENYGQEFALAA"),
    TmrnaTagEntry::new("Pseudomonas fluorescens 3 (Pf-5)", "ANDETYGDYALAA"),
    TmrnaTagEntry::new("Pseudomonas fulva", "ANDENYEGYALAA"),
    TmrnaTagEntry::new("Pseudomonas mendocina", "ANDDNYALAA"),
    TmrnaTagEntry::new("Pseudomonas protegens", "ANDETYGDYALAA"),
    TmrnaTagEntry::new("Pseudomonas putida 1", "ANDENYGAEYKLAA"),
    TmrnaTagEntry::new("Pseudomonas stutzeri", "ANDDNYEGYALAA"),
    TmrnaTagEntry::new("Pseudomonas syringae 1", "ANDENYGAQLAA"),
    TmrnaTagEntry::new("Pseudomonas syringae 2", "ANDETYGEYALAA"),
    TmrnaTagEntry::new("Pseudomonas syringae 3", "ANDENYGAQLAA"),
    TmrnaTagEntry::new("Pseudonocardia dioxanivorans", "ADKSQRAYALAA"),
    TmrnaTagEntry::new("Pseudovibrio sp. JE062", "ANDNYAMDNAVAA"),
    TmrnaTagEntry::new("Pseudoxanthomonas spadix", "ANDDNYGSDFALAA"),
    TmrnaTagEntry::new("Pseudoxanthomonas suwonensis", "ANDDNYALAA"),
    TmrnaTagEntry::new("Psychrobacter 2734", "ANDENYALAA"),
    TmrnaTagEntry::new("Psychrobacter arcticus", "ANDENYALAA"),
    TmrnaTagEntry::new("Psychrobacter cryohalolentis", "ANDENYALAA"),
    TmrnaTagEntry::new("Psychrobacter sp. PRwf-1", "ANDETYALAA"),
    TmrnaTagEntry::new("Psychroflexus torquis", "GEDNYALAA"),
    TmrnaTagEntry::new("Psychromonas ingrahamii", "ANDSNYSLAA"),
    TmrnaTagEntry::new("Pusillimonas sp. T7-7", "ANDERFALAA"),
    TmrnaTagEntry::new("Rahnella aquatilis", "ANDENYALAA"),
    TmrnaTagEntry::new("Rahnella sp. Y9602", "ANDENYALAA"),
    TmrnaTagEntry::new("Ralstonia eutropha", "ANDERYALAA"),
    TmrnaTagEntry::new("Ralstonia metallidurans", "ANDERYALAA"),
    TmrnaTagEntry::new("Ralstonia pickettii", "ANDERYALAA"),
    TmrnaTagEntry::new("Ralstonia solanacearum", "ANDNRYQLAA"),
    TmrnaTagEntry::new("Ramlibacter tataouinensis", "ANDERFALAA"),
    TmrnaTagEntry::new("Renibacterium salmoninarum", "ANSKRTDFALAA"),
    TmrnaTagEntry::new("Rhizobium etli", "ANDNYAEARLAA"),
    TmrnaTagEntry::new("Rhizobium leguminosarum", "ANDNYAEARLAA"),
    TmrnaTagEntry::new("Rhodobacter capsulatus", "ANDNRAPVALAA"),
    TmrnaTagEntry::new("Rhodobacter sphaeroides", "ANDNRAPVALAA"),
    TmrnaTagEntry::new("Rhodococcus equi", "AESTQREYALAA"),
    TmrnaTagEntry::new("Rhodococcus erythropolis", "ADSNQRDYALAA"),
    TmrnaTagEntry::new("Rhodococcus jostii", "ADSNQRDYALAA"),
    TmrnaTagEntry::new("Rhodococcus opacus", "ADSNQRDYALAA"),
    TmrnaTagEntry::new("Rhodoferax ferrireducens", "ANDERFALAA"),
    TmrnaTagEntry::new("Rhodomicrobium vannielii", "ANDNYAGARPVAIAA"),
    TmrnaTagEntry::new("Rhodomonas salina", "ANNIVPFSRKVALV"),
    TmrnaTagEntry::new("Rhodopirellula baltica", "AEENFALAA"),
    TmrnaTagEntry::new("Rhodopseudomonas palustris", "ANDNYAPVAQAA"),
    TmrnaTagEntry::new("Rhodopseudomonas palustris 4", "ANDNVRMNEVRLAA"),
    TmrnaTagEntry::new("Rhodospirillum centenum", "ANDNTAPALRMAA"),
    TmrnaTagEntry::new("Rhodospirillum photometricum", "ANDNVELAAAA"),
    TmrnaTagEntry::new("Rhodospirillum rubrum", "ANDNVELAAAA"),
    TmrnaTagEntry::new("Rhodothermus marinus", "ANDYSYAMAA"),
    TmrnaTagEntry::new("Rickettsia africae", "ANDNNRSVGHLALAA"),
    TmrnaTagEntry::new("Rickettsia amblyommii", "ANDNNRSVGRLALAA"),
    TmrnaTagEntry::new("Rickettsia australis", "ANDNNRSVDLALAA"),
    TmrnaTagEntry::new("Rickettsia bellii", "ANDNYRSAGTPALAVA"),
    TmrnaTagEntry::new("Rickettsia conorii", "ANDNNRSVGHLALAA"),
    TmrnaTagEntry::new("Rickettsia heilongjiangensis", "ANDNNRSVGRLALAA"),
    TmrnaTagEntry::new("Rickettsia massiliae", "ANDNNRSVGRLALAA"),
    TmrnaTagEntry::new("Rickettsia montanensis", "ANDNNRSVGRLALAA"),
    TmrnaTagEntry::new("Rickettsia parkeri", "ANDNNRSVGHLALAA"),
    TmrnaTagEntry::new("Rickettsia peacockii", "ANDNNRSVGRLALAA"),
    TmrnaTagEntry::new("Rickettsia philipii", "ANDNNRSVGRLALAA"),
    TmrnaTagEntry::new("Rickettsia prowazekii", "ANDNRYVGVPALAAA"),
    TmrnaTagEntry::new("Rickettsia rhipicephali", "ANDNNRSVGRLALAA"),
    TmrnaTagEntry::new("Rickettsia rickettsii", "ANDNNRSVGRLALAA"),
    TmrnaTagEntry::new("Rickettsia sibirica", "ANDNNRSVGHLALAA"),
    TmrnaTagEntry::new("Rickettsia slovaca", "ANDNNRSVGRLALAA"),
    TmrnaTagEntry::new("Rickettsia typhi", "ANDNKRYVGVAALAAA"),
    TmrnaTagEntry::new("Riemerella anatipestifer", "GNEEFALAA"),
    TmrnaTagEntry::new("Riesia pediculicola", "AKTKNYAYAQAA"),
    TmrnaTagEntry::new("Robiginitalea biformata", "GDNNYALAA"),
    TmrnaTagEntry::new("Roseburia hominis", "AEDNLAYAA"),
    TmrnaTagEntry::new("Roseiflexus castenholzii", "ANNNKVVAFKPAMALAA"),
    TmrnaTagEntry::new("Roseiflexus sp. RS-1", "ANTNKVVAFKPAMALAA"),
    TmrnaTagEntry::new("Roseobacter denitrificans", "ANDNRAPVAMAA"),
    TmrnaTagEntry::new("Roseobacter litoralis", "ANDNRAPVAMAA"),
    TmrnaTagEntry::new("Rothia dentocariosa", "AKSKRTDFALAA"),
    TmrnaTagEntry::new("Rothia mucilaginosa", "AESKRTDFALAA"),
    TmrnaTagEntry::new("Rubrivivax gelatinosus", "ANDERFALAA"),
    TmrnaTagEntry::new("Rubrobacter xylanophilus", "ANDREMALAA"),
    TmrnaTagEntry::new("Ruegeria pomeroyi", "ANDNRAPVALAA"),
    TmrnaTagEntry::new("Ruegeria sp. TM1040", "ANDNRAPVALAA"),
    TmrnaTagEntry::new("Ruminococcus albus", "GHGYFAKAS"),
    TmrnaTagEntry::new("Ruminococcus albus", "DNDNFAMAA"),
    TmrnaTagEntry::new("Runella slithyformis", "GEYSYAMAA"),
    TmrnaTagEntry::new("Ruthia magnifica", "ANENNYALAA"),
    TmrnaTagEntry::new("Saccharomonospora viridis", "AKTNSQRDFALAA"),
    TmrnaTagEntry::new("Saccharophagus degradans", "ANDDNYGAQLAA"),
    TmrnaTagEntry::new("Saccharopolyspora erythraea", "ADKSQREFALAA"),
    TmrnaTagEntry::new("Salinibacter ruber", "ADDYSYAMAA"),
    TmrnaTagEntry::new("Salinispora arenicola", "AKQNRADFALAA"),
    TmrnaTagEntry::new("Salinispora tropica", "AKQNRADFALAA"),
    TmrnaTagEntry::new("Salmonella bongori", "ANDENYALAA"),
    TmrnaTagEntry::new("Salmonella enterica 1", "ANDETYALAA"),
    TmrnaTagEntry::new("Salmonella enterica 2", "ANDENYALAA"),
    TmrnaTagEntry::new("Salmonella enterica 3", "ANDETYALAA"),
    TmrnaTagEntry::new("Salmonella enterica 5", "ANDETYALAA"),
    TmrnaTagEntry::new("Salmonella enterica 6", "ANDENYALAA"),
    TmrnaTagEntry::new("Salmonella paratyphi", "ANDENYALAA"),
    TmrnaTagEntry::new("Salmonella typhimurium", "ANDETYALAA"),
    TmrnaTagEntry::new("Salmonella typhi", "ANDETYALAA"),
    TmrnaTagEntry::new("Sanguibacter keddieii", "ADSKRTDFALAA"),
    TmrnaTagEntry::new("Saprospira grandis", "GNTNYALAA"),
    TmrnaTagEntry::new("Sebaldella termitidis", "GNDNYALAA"),
    TmrnaTagEntry::new("secondary endosymbiont", "ANDSQFESKTALAA"),
    TmrnaTagEntry::new("Segniliparus rotundus", "ADTTQRDYALAA"),
    TmrnaTagEntry::new("Selenomonas ruminantium", "DEFDYAYAA"),
    TmrnaTagEntry::new("Selenomonas sputigena", "ANEDYALAA"),
    TmrnaTagEntry::new("Serratia marcescens", "ANDENYALAA"),
    TmrnaTagEntry::new("Serratia plymuthica", "ANDSQFESAALAA"),
    TmrnaTagEntry::new("Serratia proteamaculans", "ANDSQFESAALAA"),
    TmrnaTagEntry::new("Serratia symbiotica", "ANDENYALAA"),
    TmrnaTagEntry::new("Shewanella amazonensis", "ANDDNYALAA"),
    TmrnaTagEntry::new("Shewanella ANA-3", "ANDDNYALAA"),
    TmrnaTagEntry::new("Shewanella baltica", "ANDSNYSLAA"),
    TmrnaTagEntry::new("Shewanella denitrificans", "ANDSNYSLAA"),
    TmrnaTagEntry::new("Shewanella frigidimarina", "ANDSNYSLAA"),
    TmrnaTagEntry::new("Shewanella halifaxensis", "ANDSNYSLAA"),
    TmrnaTagEntry::new("Shewanella loihica", "ANDDNYALAA"),
    TmrnaTagEntry::new("Shewanella oneidensis", "ANDDNYALAA"),
    TmrnaTagEntry::new("Shewanella pealeana", "ANDSNYSLAA"),
    TmrnaTagEntry::new("Shewanella piezotolerans", "ANDDNYSLAA"),
    TmrnaTagEntry::new("Shewanella putrefaciens", "ANDDNYALAA"),
    TmrnaTagEntry::new("Shewanella PV-4", "ANDDNYALAA"),
    TmrnaTagEntry::new("Shewanella SAR-1", "ANDDNYALAA"),
    TmrnaTagEntry::new("Shewanella SAR-1, version 2", "ANNDNYALAA"),
    TmrnaTagEntry::new("Shewanella SAR-2, version 2", "ADYGYMAAA"),
    TmrnaTagEntry::new("Shewanella sediminis", "ANDSNYSLAA"),
    TmrnaTagEntry::new("Shewanella sp. ANA-3", "ANDDNYALAA"),
    TmrnaTagEntry::new("Shewanella sp. MR-4", "ANDDNYALAA"),
    TmrnaTagEntry::new("Shewanella sp. MR-7", "ANDDNYALAA"),
    TmrnaTagEntry::new("Shewanella sp. W3-18-1", "ANDDNYALAA"),
    TmrnaTagEntry::new("Shewanella violacea", "ANDSNYSLAA"),
    TmrnaTagEntry::new("Shewanella woodyi", "ANDDNYALAA"),
    TmrnaTagEntry::new("Shigella boydii", "ANDENYALAA"),
    TmrnaTagEntry::new("Shigella dysenteriae 1", "ANDENYALAA"),
    TmrnaTagEntry::new("Shigella dysenteriae 2", "ANDENYALAA"),
    TmrnaTagEntry::new("Shigella flexneri", "ANDENYALAA"),
    TmrnaTagEntry::new("Shigella sonnei", "ANDENYALAA"),
    TmrnaTagEntry::new("Shimwellia blattae", "ANDENYALAA"),
    TmrnaTagEntry::new("Sideroxydans lithotrophicus", "ANDEKYALAA"),
    TmrnaTagEntry::new("Silicibacter pomeroyi", "ANDNRAPVALAA"),
    TmrnaTagEntry::new("Silicibacter TM1040", "ANDNRAPVALAA"),
    TmrnaTagEntry::new("Simiduia agarivorans", "ANDDNYGAQLAA"),
    TmrnaTagEntry::new("Simkania negevensis", "VDTTEDFYLEAA"),
    TmrnaTagEntry::new("Sinorhizobium fredii", "ANDNYAEARLAA"),
    TmrnaTagEntry::new("Sinorhizobium medicae", "ANDNYAEARLAA"),
    TmrnaTagEntry::new("Sinorhizobium meliloti", "ANDNYAEARLAA"),
    TmrnaTagEntry::new("Slackia heliotrinireducens", "GKSYNTGRMALAA"),
    TmrnaTagEntry::new("Sodalis glossinidius", "ANDSQFESNAALAA"),
    TmrnaTagEntry::new("Solibacillus silvestris", "GKQQNFAFAA"),
    TmrnaTagEntry::new("Solibacter usitatus", "ANTQFAYAA"),
    TmrnaTagEntry::new("Solitalea canadensis", "GENNYALAA"),
    TmrnaTagEntry::new("Sorangium cellulosum", "ANDNAYAVAA"),
    TmrnaTagEntry::new("Sphaerobacter thermophilus", "GNESYALAA"),
    TmrnaTagEntry::new("Sphaerochaeta coccoides", "AKKEDENVSYDAEYAFAA"),
    TmrnaTagEntry::new("Sphaerochaeta globosa", "AKKEDEVSFNAEYAFAA"),
    TmrnaTagEntry::new("Sphaerochaeta pleomorpha", "AKKEDEVSFNAEYALAA"),
    TmrnaTagEntry::new("Sphingobacterium sp. 21", "GENNYALAA"),
    TmrnaTagEntry::new("Sphingobium chlorophenolicum", "ANDNEALALAA"),
    TmrnaTagEntry::new("Sphingobium japonicum", "ANDNEALALAA"),
    TmrnaTagEntry::new("Sphingobium sp. SYK-6", "ANDNEALALAA"),
    TmrnaTagEntry::new("Sphingomonas elodea", "ANDNEALAIAA"),
    TmrnaTagEntry::new("Sphingomonas wittichii", "ANDNEALAIAA"),
    TmrnaTagEntry::new("Sphingopyxis alaskensis", "ANDNEALALAA"),
    TmrnaTagEntry::new("Spirochaeta africana", "AKNEDNVVEVAFGNDDTMLAAA"),
    TmrnaTagEntry::new("Spirochaeta smaragdinae", "ANDADYALAA"),
    TmrnaTagEntry::new("Spirochaeta thermophila", "ANDELALAA"),
    TmrnaTagEntry::new("Spiroplasma kunkelii", "ASKKQKEDKIEMPAFMMNNQLAVSMLAA"),
    TmrnaTagEntry::new("Spirosoma linguale", "GEYNYAMAA"),
    TmrnaTagEntry::new("Stackebrandtia nassauensis", "AKTESRSSFALAA"),
    TmrnaTagEntry::new("Staphylococcus aureus", "GKSNNNFAVAA"),
    TmrnaTagEntry::new("Staphylococcus carnosus", "GKTNNNLAVAA"),
    TmrnaTagEntry::new("Staphylococcus epidermidis", "DKSNNNFAVAA"),
    TmrnaTagEntry::new("Staphylococcus haemolyticus", "DKSNNNFAVAA"),
    TmrnaTagEntry::new("Staphylococcus lugdunensis", "GKSNNNFAVAA"),
    TmrnaTagEntry::new("Staphylococcus pseudintermedius", "GKTNNNFAVAA"),
    TmrnaTagEntry::new("Staphylococcus saprophyticus", "GKENNNFAVAA"),
    TmrnaTagEntry::new("Staphylococcus xylosus", "GKENNNFAVAA"),
    TmrnaTagEntry::new("Starkeya novella", "ANDNYAPVAQAA"),
    TmrnaTagEntry::new("Stenotrophomonas maltophilia", "ANDDNYALAA"),
    TmrnaTagEntry::new("Stigmatella aurantiaca", "DGKDTKANDNVELALAA"),
    TmrnaTagEntry::new("Streptobacillus moniliformis", "GKNNFALAA"),
    TmrnaTagEntry::new("Streptococcus agalactiae", "AKNTNSYALAA"),
    TmrnaTagEntry::new("Streptococcus bovis", "AKNTNSYAVAA"),
    TmrnaTagEntry::new("Streptococcus constellatus", "AKNNNSYALAA"),
    TmrnaTagEntry::new("Streptococcus criceti", "AKNTNSYAVAA"),
    TmrnaTagEntry::new("Streptococcus dysgalactiae", "AKNTNSYALAA"),
    TmrnaTagEntry::new("Streptococcus equi", "AKNNTTYALAA"),
    TmrnaTagEntry::new("Streptococcus gallolyticus", "AKNTNSYAVAA"),
    TmrnaTagEntry::new("Streptococcus gordonii", "AKNNTSYALAA"),
    TmrnaTagEntry::new("Streptococcus macedonicus", "AKNTNSYAVAA"),
    TmrnaTagEntry::new("Streptococcus mitis", "AKNNTSYALAA"),
    TmrnaTagEntry::new("Streptococcus mutans", "AKNTNSYAVAA"),
    TmrnaTagEntry::new("Streptococcus oralis", "AKNNTSYALAA"),
    TmrnaTagEntry::new("Streptococcus parasanguinis", "AKNNNSYALAA"),
    TmrnaTagEntry::new("Streptococcus parauberis", "AKNTNTYALAA"),
    TmrnaTagEntry::new("Streptococcus pneumoniae", "AKNNTSYALAA"),
    TmrnaTagEntry::new("Streptococcus pseudopneumoniae", "AKNNTSYALAA"),
    TmrnaTagEntry::new("Streptococcus pyogenes", "AKNTNSYALAA"),
    TmrnaTagEntry::new("Streptococcus salivarius", "AQLNITAKNTNSYAVAA"),
    TmrnaTagEntry::new("Streptococcus sanguinis", "AKNNNSYALAA"),
    TmrnaTagEntry::new("Streptococcus sobrinus", "AKNTNSYAVAA"),
    TmrnaTagEntry::new("Streptococcus suis", "AKNTNTYALAA"),
    TmrnaTagEntry::new("Streptococcus thermophilus", "AKNTNSYAVAA"),
    TmrnaTagEntry::new("Streptococcus uberis", "AKNTNSYALAA"),
    TmrnaTagEntry::new("Streptococcus zooepidemicus", "AKNNTTYALAA"),
    TmrnaTagEntry::new("Streptomyces aureofaciens", "ANSKRDSQQFALAA"),
    TmrnaTagEntry::new("Streptomyces avermitilis", "ANTKSDSQSFALAA"),
    TmrnaTagEntry::new("Streptomyces avermitilus", "ANTKSDSQSFALAA"),
    TmrnaTagEntry::new("Streptomyces bingchenggensis", "ANTKRDSFALAA"),
    TmrnaTagEntry::new("Streptomyces cattleya", "ANNKRDSFALAA"),
    TmrnaTagEntry::new("Streptomyces coelicolor", "ANTKRDSSQQAFALAA"),
    TmrnaTagEntry::new("Streptomyces collinus", "ANTKRDSSSFALAA"),
    TmrnaTagEntry::new("Streptomyces flavogriseus", "ANSKRDSSAFALAA"),
    TmrnaTagEntry::new("Streptomyces griseus", "ANSKRDSSAFALAA"),
    TmrnaTagEntry::new("Streptomyces hygroscopicus", "ANTKRDSFALAA"),
    TmrnaTagEntry::new("Streptomyces lividans", "ANTKRDSSQQAFALAA"),
    TmrnaTagEntry::new("Streptomyces scabiei", "ANSKSDSPQQQFSLAA"),
    TmrnaTagEntry::new("Streptomyces sp. SirexAA-E", "ANTKRDSSAFALAA"),
    TmrnaTagEntry::new("Streptomyces thermophilus", "AKNTNSYAVAA"),
    TmrnaTagEntry::new("Streptomyces venezuelae", "ANSKSDNSRFALAA"),
    TmrnaTagEntry::new("Streptomyces violaceusniger", "ANTKRDSFALAA"),
    TmrnaTagEntry::new("Streptosporangium roseum", "ANKTHSEVSQGNLALAA"),
    TmrnaTagEntry::new("Sulcia muelleri", "GKKNYALAA"),
    TmrnaTagEntry::new("Sulfuricurvum kujiense", "ANNTNYRPAYAVA"),
    TmrnaTagEntry::new("Sulfurimonas autotrophica", "ANNTNYRPALAVA"),
    TmrnaTagEntry::new("Sulfurimonas denitrificans", "ANNTNYRPAYAVA"),
    TmrnaTagEntry::new("Sulfurospirillum barnesii", "ANNSNYRPAYAVA"),
    TmrnaTagEntry::new("Sulfurospirillum deleyianum", "ANNSNYRPAYALAA"),
    TmrnaTagEntry::new("Sulfurovum sp. NBC37-1", "ANNTDYRPAYAVA"),
    TmrnaTagEntry::new("Synechococcus elongatus", "ANNIVPFARKAAPVAA"),
    TmrnaTagEntry::new("Synechococcus sp. CC9311", "ANNIVRFSRQAAPVAA"),
    TmrnaTagEntry::new("Synechococcus sp. CC9605", "ANNIVRFSRQAAPVAA"),
    TmrnaTagEntry::new("Synechococcus sp. CC9902", "ANNIVRFSRQAAPVAA"),
    TmrnaTagEntry::new("Synechococcus sp. JA-2-3B'a(2-13)", "ANNVVPFARKAAALAA"),
    TmrnaTagEntry::new("Synechococcus sp. JA-3-3Ab (version 1)", "ANNVVPFARKAAALAA"),
    TmrnaTagEntry::new("Synechococcus sp. JA-3-3Ab (version 2)", "ANNVVPFARKAAALAA"),
    TmrnaTagEntry::new("Synechococcus sp. PCC 6301", "ANNIVPFARKAAPVAA"),
    TmrnaTagEntry::new("Synechococcus sp. PCC 6307", "ANNIVRFSRQAAPVAA"),
    TmrnaTagEntry::new("Synechocystis sp. PCC 6803", "ANNIVSFKRVAIAA"),
    TmrnaTagEntry::new("Synechococcus sp. PCC 6904", "ANNIVRFSRQAAPVAA"),
    TmrnaTagEntry::new("Synechococcus sp. PCC 7002", "ANNIVPFARKAAAVA"),
    TmrnaTagEntry::new("Synechococcus sp. PCC 7009", "ANNIVRFSRQAAPVAA"),
    TmrnaTagEntry::new("Synechococcus sp. RCC307", "ANNIVRFSRQAAPVAA"),
    TmrnaTagEntry::new("Synechococcus sp. WH 7803", "ANNIVRFSRQAAPVAA"),
    TmrnaTagEntry::new("Synechococcus sp. WH 8102", "ANNIVRFSRHAAPVAA"),
    TmrnaTagEntry::new("Syntrophobacter fumaroxidans", "ADDYAYAVAA"),
    TmrnaTagEntry::new("Syntrophomonas wolfei", "AEDNFALAA"),
    TmrnaTagEntry::new("Syntrophothermus lipocalidus", "ANNELALAA"),
    TmrnaTagEntry::new("Syntrophus aciditrophicus", "ANDYEYALAA"),
    TmrnaTagEntry::new("Tannerella forsythensis", "GENNYALAA"),
    TmrnaTagEntry::new("Tannerella forsythia", "GENNYALAA"),
    TmrnaTagEntry::new("Taylorella asinigenitalis", "ANDDKFALAA"),
    TmrnaTagEntry::new("Taylorella equigenitalis", "ANDENFALAA"),
    TmrnaTagEntry::new("Tepidanaerobacter acetatoxydans", "ANNDLAYAA"),
    TmrnaTagEntry::new("Teredinibacter turnerae", "ANDDNYGAQLAA"),
    TmrnaTagEntry::new("Terriglobus roseus", "AEPQFALAA"),
    TmrnaTagEntry::new("Terriglobus saanensis", "AEPQFALAA"),
    TmrnaTagEntry::new("Tetragenococcus halophilus", "AKNNNNSYALAA"),
    TmrnaTagEntry::new("Thalassiosira pseudonana chloroplast", "ANNIMPFMFNVVKTNRSLTTLNFAV"),
    TmrnaTagEntry::new("Thalassiosira weissflogii chloroplast", "ANNIIPFIFKAVKTKKEAMALNFAV"),
    TmrnaTagEntry::new("Thauera sp. MZ1T", "ANDERFALAA"),
    TmrnaTagEntry::new("Thermacetogenium phaeum", "ANNEYALAA"),
    TmrnaTagEntry::new("Thermaerobacter marianensis", "ANEELALAA"),
    TmrnaTagEntry::new("Thermanaerovibrio acidaminovorans", "ANDNYALAA"),
    TmrnaTagEntry::new("Thermincola potens", "AEENYALAA"),
    TmrnaTagEntry::new("Thermoanaerobacter italicus", "ADRELAYAA"),
    TmrnaTagEntry::new("Thermoanaerobacter mathranii", "ADRELAYAA"),
    TmrnaTagEntry::new("Thermoanaerobacter pseudethanolicus", "ADRELAYAA"),
    TmrnaTagEntry::new("Thermoanaerobacter sp. X514", "ADRELAYAA"),
    TmrnaTagEntry::new("Thermoanaerobacter tengcongensis", "ADRELAYAA"),
    TmrnaTagEntry::new("Thermoanaerobacter wiegelii", "ADRELAYAA"),
    TmrnaTagEntry::new("Thermoanaerobacterium saccharolyticum", "ANDNLAYAA"),
    TmrnaTagEntry::new("Thermoanaerobacterium thermosaccharolyticum", "ANNDNLAYAA"),
    TmrnaTagEntry::new("Thermoanaerobacterium xylanolyticum", "ANDNLAYAA"),
    TmrnaTagEntry::new("Thermobaculum terrenum", "ANTEYALAA"),
    TmrnaTagEntry::new("Thermobifida fusca", "ANSKRTEFALAA"),
    TmrnaTagEntry::new("Thermobispora bispora", "ANKKHAEVSQASLALAA"),
    TmrnaTagEntry::new("Thermodesulfatator indicus", "ADEYNYAMAA"),
    TmrnaTagEntry::new("Thermodesulfobacterium commune", "ANEYAYALAA"),
    TmrnaTagEntry::new("Thermodesulfobacterium geofontis", "ADEYSYALAA"),
    TmrnaTagEntry::new("Thermodesulfobium narugense", "ANNNSLALAA"),
    TmrnaTagEntry::new("Thermodesulfovibrio yellowstonii", "ANNELALAA"),
    TmrnaTagEntry::new("Thermomicrobium roseum", "GERELALAA"),
    TmrnaTagEntry::new("Thermomonospora curvata", "ANKKQSEFALAA"),
    TmrnaTagEntry::new("Thermosediminibacter oceani", "ANEELALAA"),
    TmrnaTagEntry::new("Thermosipho africanus", "ANEELALAA"),
    TmrnaTagEntry::new("Thermosipho melanesiensis", "ANEEIALAA"),
    TmrnaTagEntry::new("Thermosynechococcus elongatus", "ANNIVPFARKAAAVA"),
    TmrnaTagEntry::new("Thermotoga lettingae", "ANNELALAA"),
    TmrnaTagEntry::new("Thermotoga maritima ", "ANEPVAVAA"),
    TmrnaTagEntry::new("Thermotoga neapolitana", "ANEPVAVAA"),
    TmrnaTagEntry::new("Thermotoga petrophila", "ANEPVAVAA"),
    TmrnaTagEntry::new("Thermotoga sp. RQ2", "ANEPVAVAA"),
    TmrnaTagEntry::new("Thermotoga thermarum", "ANEELALAA"),
    TmrnaTagEntry::new("Thermovibrio ammonificans", "ADETLALAA"),
    TmrnaTagEntry::new("Thermovirga lienii", "ANENYALAA"),
    TmrnaTagEntry::new("Thermus oshimai", "ANKPAYALAA"),
    TmrnaTagEntry::new("Thermus scotoductus", "ANKPAYALAA"),
    TmrnaTagEntry::new("Thermus sp. CCB_US3_UF1", "ANKPAYALAA"),
    TmrnaTagEntry::new("Thermus thermophilus", "ANTNYALAA"),
    TmrnaTagEntry::new("Thioalkalimicrobium cyclicum", "ANDDNYALAA"),
    TmrnaTagEntry::new("Thioalkalivibrio sp. K90mix", "ANDDNYALAA"),
    TmrnaTagEntry::new("Thiobacillus denitrificans", "AKSKAARRNPACSAGVMELKA"),
    TmrnaTagEntry::new("Thiocystis violascens", "ANDDNYALAA"),
    TmrnaTagEntry::new("Thiomicrospira crunogena", "ANDDNYALAA"),
    TmrnaTagEntry::new("Thiomonas intermedia", "ANDSSYALAA"),
    TmrnaTagEntry::new("Thiomonas sp. 3As", "ANDSSYALAA"),
    TmrnaTagEntry::new("Tistrella mobilis", "ANDNRVALAA"),
    TmrnaTagEntry::new("Tolumonas auensis", "ANDETYALAA"),
    TmrnaTagEntry::new("Tremblaya princeps 1 (Dysmicoccus)", "APSNRFTIVANDCIDALVRRAVV"),
    TmrnaTagEntry::new("Treponema azotonutricium", "ADNDNYNYALAA"),
    TmrnaTagEntry::new("Treponema brennaborense", "AEDNRQFALAA"),
    TmrnaTagEntry::new("Treponema caldaria", "ADNDSYALAA"),
    TmrnaTagEntry::new("Treponema denticola", "AENNDSFDYALAA"),
    TmrnaTagEntry::new("Treponema pallidum", "ANSDSFDYALAA"),
    TmrnaTagEntry::new("Treponema primitia", "ANNDSYAFAA"),
    TmrnaTagEntry::new("Treponema succinifaciens", "AKRREDEQSENEQFALAA"),
    TmrnaTagEntry::new("Trichodesmium erythraeum", "ANNIVPFARKQVAALA"),
    TmrnaTagEntry::new("Tropheryma whipplei", "ANLKRTDLSLAA"),
    TmrnaTagEntry::new("Truepera radiovictrix", "GNSNSYALAA"),
    TmrnaTagEntry::new("Tsukamurella paurometabola", "ADSNQRDFALAA"),
    TmrnaTagEntry::new("Turneriella parva", "AENETYALAA"),
    TmrnaTagEntry::new("uncultured bacterium", "ANDNFAPVAVAA"),
    TmrnaTagEntry::new("Uncultured ciona", "ANDEFFDARLRA"),
    TmrnaTagEntry::new("Uncultured FS1", "ANDETYALAA"),
    TmrnaTagEntry::new("Uncultured FS2", "ANDENYALAA"),
    TmrnaTagEntry::new("Uncultured LEM1", "ANDETYALAA"),
    TmrnaTagEntry::new("Uncultured LEM2", "ANDETHALAA"),
    TmrnaTagEntry::new("Uncultured marineEBAC20E09", "ANNDNYALAA"),
    TmrnaTagEntry::new("Uncultured phakopsora", "ANDNSYALAA"),
    TmrnaTagEntry::new("Uncultured QL1", "ANVENYALAA"),
    TmrnaTagEntry::new("Uncultured RCA1", "ANDENYALAA"),
    TmrnaTagEntry::new("Uncultured RCA2", "SNDENYALAA"),
    TmrnaTagEntry::new("Uncultured RCA4", "ANDETYALAA"),
    TmrnaTagEntry::new("Uncultured remanei", "ANDESYALAA"),
    TmrnaTagEntry::new("Uncultured stronglyoides1", "ANDERFALAA"),
    TmrnaTagEntry::new("Uncultured U01a", "ANDSNYALAA"),
    TmrnaTagEntry::new("Uncultured U02", "ANDEQFALAA"),
    TmrnaTagEntry::new("Uncultured U04", "ANDETYALAA"),
    TmrnaTagEntry::new("Uncultured VLS13", "ANDENYALAA"),
    TmrnaTagEntry::new("Uncultured VLS1", "ANDENYALAA"),
    TmrnaTagEntry::new("Uncultured VLS5", "ANDETYALAA"),
    TmrnaTagEntry::new("Uncultured VLS6", "ANDENYALAA"),
    TmrnaTagEntry::new("Uncultured VLS7", "ANDENYALAA"),
    TmrnaTagEntry::new("Uncultured VLS9", "ANDENYALAA"),
    TmrnaTagEntry::new("Uncultured VLW1", "ANDENYALAA"),
    TmrnaTagEntry::new("Uncultured VLW2", "ANDENYALAA"),
    TmrnaTagEntry::new("Uncultured VLW3", "ANDENYALAA"),
    TmrnaTagEntry::new("Uncultured VLW5", "ANDENYALAA"),
    TmrnaTagEntry::new("Uncultured WW10", "ANDENYALAV"),
    TmrnaTagEntry::new("Uncultured WW11", "ANDDNYALAA"),
    TmrnaTagEntry::new("Uncultured WW1", "ANDENYALAA"),
    TmrnaTagEntry::new("Uncultured WW2", "ANDENYALAA"),
    TmrnaTagEntry::new("Uncultured WW4", "ANDGNYALAA"),
    TmrnaTagEntry::new("Uncultured WW5", "ANDENYALAA"),
    TmrnaTagEntry::new("Uncultured WW7", "ANDENCALAA"),
    TmrnaTagEntry::new("Uncultured WW8", "ANDENYALAA"),
    TmrnaTagEntry::new("Uncultured WW9", "ANDENYALAA"),
    TmrnaTagEntry::new("Ureaplasma parvum", "AENKKSSEVELNPAFMASATNANYAFAY"),
    TmrnaTagEntry::new("Ureaplasma urealyticum", "AENKKSSEVELNPAFMASATNANYAFAY"),
    TmrnaTagEntry::new("Variovorax paradoxus", "ANDERFALAA"),
    TmrnaTagEntry::new("Veillonella parvula", "AEENFALAA"),
    TmrnaTagEntry::new("Verminephrobacter eiseniae", "ANDERFALAA"),
    TmrnaTagEntry::new("Verrucomicrobium spinosum", "ANSNELALAA"),
    TmrnaTagEntry::new("Verrucosispora maris", "AKHNRADFALAA"),
    TmrnaTagEntry::new("Vesicomyosocius okutanii", "ENENNYALAA"),
    TmrnaTagEntry::new("Vibrio anguillarum", "ANDENYALAA"),
    TmrnaTagEntry::new("Vibrio campbellii", "ANDENYALAA"),
    TmrnaTagEntry::new("Vibrio cholerae", "ANDENYALAA"),
    TmrnaTagEntry::new("Vibrio Ex25", "ANDENYALAA"),
    TmrnaTagEntry::new("Vibrio fischeri", "ANDENYALAA"),
    TmrnaTagEntry::new("Vibrio furnissii", "ANDENYALAA"),
    TmrnaTagEntry::new("Vibrio parahaemolyticus", "ANDENYALAA"),
    TmrnaTagEntry::new("Vibrio parahemolyticus", "ANDENYALAA"),
    TmrnaTagEntry::new("Vibrio sp. EJY3", "ANDENYALAA"),
    TmrnaTagEntry::new("Vibrio sp. Ex25", "ANDENYALAA"),
    TmrnaTagEntry::new("Vibrio splendidus", "ANDENYALAA"),
    TmrnaTagEntry::new("Vibrio vulnificus", "ANDENYALAA"),
    TmrnaTagEntry::new("Waddlia chondrophila", "ADLDLATAAVAA"),
    TmrnaTagEntry::new("Weeksella virosa", "GNEEYALAA"),
    TmrnaTagEntry::new("Weissella koreensis", "AKNSNNLAFAA"),
    TmrnaTagEntry::new("Wigglesworthia brevipalpis", "AKHKYNEPALLAA"),
    TmrnaTagEntry::new("Wigglesworthia glossinidia", "AKHKYNEPALLAA"),
    TmrnaTagEntry::new("Wolbachi.sp", "ANDNFAAEDNVDAIAA"),
    TmrnaTagEntry::new("Wolbachia endosymbiont", "ANDNFAAEEYRVAA"),
    TmrnaTagEntry::new("Wolbachia sp. 2 (Brugi)", "ANDNFAAEGDVAVAA"),
    TmrnaTagEntry::new("Wolbachia sp. 3 (Culex)", "ANDNFAAEDNVALAA"),
    TmrnaTagEntry::new("Wolbachia sp. 4 (Dros.)", "ANDNFAAEEYRVAA"),
    TmrnaTagEntry::new("Wolinella succinogenes", "ALSSHPKRGKRLGLPITSALGA"),
    TmrnaTagEntry::new("Xanthobacter autotrophicus", "ANDNYAPVAQAA"),
    TmrnaTagEntry::new("Xanthomonas albilineans", "ANDDNYALAA"),
    TmrnaTagEntry::new("Xanthomonas axonopodis", "ANDDNYGSDFAIAA"),
    TmrnaTagEntry::new("Xanthomonas campestris 1", "ANDDNYGSDFAIAA"),
    TmrnaTagEntry::new("Xanthomonas campestris 2", "ANDDNYGSDSAIAA"),
    TmrnaTagEntry::new("Xanthomonas oryzae", "ANDDNYGSDFAIAA"),
    TmrnaTagEntry::new("Xenorhabdus bovienii", "ANDENYALAA"),
    TmrnaTagEntry::new("Xenorhabdus nematophila", "ANDENYALAA"),
    TmrnaTagEntry::new("Xylanimonas cellulosilytica", "ADNTRNDFALAA"),
    TmrnaTagEntry::new("Xylella fastidiosa 1", "ANEDNFAVAA"),
    TmrnaTagEntry::new("Xylella fastidiosa 2", "ANEDNFALAA"),
    TmrnaTagEntry::new("Xylella fastidiosa 3", "ANEDNFAIAA"),
    TmrnaTagEntry::new("Xylella fastidiosa 4", "ANEDNFALAA"),
    TmrnaTagEntry::new("Yersinia bercovieri", "ANDSQYESAALAA"),
    TmrnaTagEntry::new("Yersinia enterocolitica", "ANDSQYESAALAA"),
    TmrnaTagEntry::new("Yersinia frederiksenii", "ANDENYALAA"),
    TmrnaTagEntry::new("Yersinia intermedia", "ANDSQYESAALAA"),
    TmrnaTagEntry::new("Yersinia mollaretii", "ANDSQYESAALAA"),
    TmrnaTagEntry::new("Yersinia pestis", "ANDENYALAA"),
    TmrnaTagEntry::new("Yersinia pseudotuberculosis", "ANDENYALAA"),
    TmrnaTagEntry::new("Zobellia galactanivorans", "GENNYALAA"),
    TmrnaTagEntry::new("Zunongwangia profunda", "GENNYALAA"),
    ];
    
    let mut db = [TmrnaTagEntry::empty(); NTAGMAX];
    let mut i = 0;
    while i < NTAG {
        db[i] = entries[i];
        i += 1;
    }
    db
}

/// The tag database - mutable to allow runtime updates
/// C: extern tmrna_tag_entry tagdatabase[NTAGMAX];
pub static mut TAGDATABASE: [TmrnaTagEntry; NTAGMAX] = init_tagdatabase();
